#ifndef __MSGHDR_H__
#define __MSGHDR_H__

#pragma once


const DWORD DEFAULT_PACKETTYPE		=	0x2200000;
const DWORD DEFAULT_SNAPSHOTTYPE	=	0x210000;

//////////////////////////////////////////////////////////////////////////
// BEGIN PACKETTYPE

enum FL_PACKETTYPE { 
	PACKETTYPE_DEFAULT = DEFAULT_PACKETTYPE

	, PACKETTYPE_TRADE
	, PACKETTYPE_TRADEPUT
	, PACKETTYPE_TRADEPULL
	, PACKETTYPE_TRADEOK
	, PACKETTYPE_TRADECANCEL
	, PACKETTYPE_TRADEPUTGOLD
	, PACKETTYPE_TRADECLEARGOLD
	, PACKETTYPE_QUERYSETPLAYERNAME
	, PACKETTYPE_CONN
	, PACKETTYPE_PING
	, PACKETTYPE_CLOSE_EXISTING_CONNECTION
	, PACKETTYPE_ONE_HOUR_NOTIFY
	, PACKETTYPE_KEEP_ALIVE
	, PACKETTYPE_RUNEQ
	, PACKETTYPE_QUERYPOSTMAIL
	, PACKETTYPE_QUERYREMOVEMAIL
	, PACKETTYPE_QUERYGETMAILITEM
	, PACKETTYPE_QUERYMAILBOX
	, PACKETTYPE_ALLMAIL
	, PACKETTYPE_QUERYGETMAILGOLD
	, PACKETTYPE_READMAIL
	, PACKETTYPE_DO_ESCAPE
	, PACKETTYPE_SETSNOOP
	, PACKETTYPE_SETSNOOPGUILD
	, PACKETTYPE_SNOOP
	, PACKETTYPE_CREATEMONSTER
	, PACKETTYPE_QUERY_DESTROY_PLAYER
	, PACKETTYPE_NEW_ACCOUNT
	, PACKETTYPE_DEL_ACCOUNT
	, PACKETTYPE_CACHE_ADDR
	, PACKETTYPE_PLAYER_LIST
	, PACKETTYPE_CREATE_PLAYER
	, PACKETTYPE_DEL_PLAYER
	, PACKETTYPE_GETPLAYERLIST
	, PACKETTYPE_SEL_PLAYER
	, PACKETTYPE_SAVE_PLAYER
	, PACKETTYPE_GT
	, PACKETTYPE_MYREG
	, PACKETTYPE_PROCSERVER_LIST
	, PACKETTYPE_LOAD_WORLD
	, PACKETTYPE_RECHARGE_IDSTACK
	, PACKETTYPE_PASSAGE
	, PACKETTYPE_DUPLICATE
	, PACKETTYPE_UNIFY
	, PACKETTYPE_ID
	, PACKETTYPE_ADDID
	, PACKETTYPE_POLL
	, PACKETTYPE_QUERYTICKCOUNT
	, PACKETTYPE_ERROR_TEXT
	, PACKETTYPE_PLAYERCOUNT
	, PACKETTYPE_QUERYSETGUILDNAME
	, PACKETTYPE_AUTHQUERY
	, PACKETTYPE_ALLPLAYERID
	, PACKETTYPE_BUSY
	, PACKETTYPE_CERTIFY
	, PACKETTYPE_SERVER_LIST
	, PACKETTYPE_ERROR
	, PACKETTYPE_PLAYERID
	, PACKETTYPE_REMOVEPLAYERID
	, PACKETTYPE_PLAYER_COUNT
	, PACKETTYPE_ENABLE_SERVER
	, PACKETTYPE_FAIL
	, PACKETTYPE_NEWYEAR
	, PACKETTYPE_EXPBOXINFO
	, PACKETTYPE_MOVERDEATH
	, PACKETTYPE_MELEE_ATTACK2
	, PACKETTYPE_SHIP_ACTMSG
	, PACKETTYPE_MOTION
	, PACKETTYPE_SETFXP
	, PACKETTYPE_SETNAVIPOINT
	, PACKETTYPE_REMOVEINVENITEM
	, PACKETTYPE_USESKILL
	, PACKETTYPE_DOUSEITEM
	, PACKETTYPE_SFX_ID
	, PACKETTYPE_SETTARGET
	, PACKETTYPE_SFX_CLEAR
	, PACKETTYPE_TELESKILL
	, PACKETTYPE_REMOVEQUEST
	, PACKETTYPE_CHANGEJOB
	, PACKETTYPE_ITEM_TBL_UPDATE
	, PACKETTYPE_JOIN
	, PACKETTYPE_LEAVE
	, PACKETTYPE_DESTROY_ALLPLAYERS
	, PACKETTYPE_REMOVE_ALLACCOUNTS
	, PACKETTYPE_CLOSE_ERROR
	, PACKETTYPE_PRE_JOIN
	, PACKETTYPE_GAMERATE
	, PACKETTYPE_SEND_TO_CLIENT_NOTICE
	, PACKETTYPE_SEND_TO_CLIENT_FILE_LIST
	, PACKETTYPE_SEND_TO_SERVER_PATCH
	, PACKETTYPE_SEND_TO_CLIENT_FILE
	, PACKETTYPE_SEND_TO_CLIENT_PATCH
	, PACKETTYPE_SEND_TO_CLIENT_PATCH_END
	, PACKETTYPE_SEND_TO_CLIENT_PATCHCLIENTINFO
	, PACKETTYPE_SEND_TO_SERVER_PATCHCLIENT_CORRECT
	, PACKETTYPE_SEND_TO_SERVER_PATCHCLIENT_INCORRECT
	, PACKETTYPE_SEND_TO_CLIENT_PATCHCLIENT
	, PACKETTYPE_SEND_TO_SERVER_REQUIRE_FILE
	, PACKETTYPE_SEND_TO_SERVER_REQUIRE_FILE_LIST
	, PACKETTYPE_SEND_TO_CLIENT_CDN
	, PACKETTYPE_SEND_TO_SERVER_EXP
	, PACKETTYPE_SEND_TO_SERVER_CHANGEJOB
	, PACKETTYPE_SEND_TO_SERVER_AP
	, PACKETTYPE_SETEXPERIENCE
	, PACKETTYPE_REMOVEVENDORITEM
	, PACKETTYPE_REMOVEALLITEM
	, PACKETTYPE_MELEE_ATTACK
	, PACKETTYPE_MAGIC_ATTACK
	, PACKETTYPE_RANGE_ATTACK
	, PACKETTYPE_SETMONSTERRESPAWN
	, PACKETTYPE_SETITEMEVENT
	, PACKETTYPE_LOADCONSTANT
	, PACKETTYPE_CHAT
	, PACKETTYPE_ACTMSG
	, PACKETTYPE_ADDOBJ
	, PACKETTYPE_REMOVEOBJ
	, PACKETTYPE_CONTROL
	, PACKETTYPE_BROADCAST
	, PACKETTYPE_SAVEALLPLAYERS
	, PACKETTYPE_DOUSESKILLPOINT
	, PACKETTYPE_SKILLPOINTLOG
	, PACKETTYPE_CREATEITEM
	, PACKETTYPE_MOVEITEM
	, PACKETTYPE_DROPITEM
	, PACKETTYPE_DROPGOLD
	, PACKETTYPE_REMOVEITEM
	, PACKETTYPE_SYNCITEM
	, PACKETTYPE_DOEQUIP
	, PACKETTYPE_DAMAGE
	, PACKETTYPE_TRADECONFIRM
	, PACKETTYPE_CONFIRMTRADE
	, PACKETTYPE_CONFIRMTRADECANCEL
	, PACKETTYPE_PVENDOR_OPEN
	, PACKETTYPE_PVENDOR_CLOSE
	, PACKETTYPE_REGISTER_PVENDOR_ITEM
	, PACKETTYPE_QUERY_PVENDOR_ITEM
	, PACKETTYPE_BUY_PVENDOR_ITEM
	, PACKETTYPE_UNREGISTER_PVENDOR_ITEM
	, PACKETTYPE_SET_HAIR
	, PACKETTYPE_SCRIPTDLG
	, PACKETTYPE_OPENSHOPWND
	, PACKETTYPE_CLOSESHOPWND
	, PACKETTYPE_REVIVAL_BY_SKILL
	, PACKETTYPE_REVIVAL_TO_CURRENT_POS
	, PACKETTYPE_REVIVAL_TO_LODESTAR
	, PACKETTYPE_REVIVAL_TO_LODELIGHT
	, PACKETTYPE_NW_WANTED_LIST
	, PACKETTYPE_WN_WANTED_LIST
	, PACKETTYPE_NW_WANTED_INFO
	, PACKETTYPE_WN_WANTED_INFO
	, PACKETTYPE_WC_WANTED_GOLD
	, PACKETTYPE_WC_WANTED_REWARD
	, PACKETTYPE_CW_WANTED_LIST
	, PACKETTYPE_CW_WANTED_REWARD
	, PACKETTYPE_BUYITEM
	, PACKETTYPE_SELLITEM
	, PACKETTYPE_REPAIRITEM
	, PACKETTYPE_BUYCHIPITEM
	, PACKETTYPE_CT_WANTED
	, PACKETTYPE_TC_LIST
	, PACKETTYPE_REQ_LEAVE
	, PACKETTYPE_WT_REQ_LEAVE
	, PACKETTYPE_NW_WANTED_NAME
	, PACKETTYPE_WN_WANTED_NAME
	, PACKETTYPE_REPLACE
	, PACKETTYPE_CORR_REQ
	, PACKETTYPE_SCRIPT_REMOVE_ALL_ITEM
	, PACKETTYPE_SCRIPT_EQUIP_ITEM
	, PACKETTYPE_SETQUEST
	, PACKETTYPE_SCRIPT_CREATE_ITEM
	, PACKETTYPE_SCRIPT_ADD_GOLD
	, PACKETTYPE_SCRIPT_REMOVE_QUEST
	, PACKETTYPE_SCRIPT_REPLACE
	, PACKETTYPE_SCRIPT_REPLACE_KEY
	, PACKETTYPE_SCRIPT_ADD_EXP
	, PACKETTYPE_SCRIPT_REMOVE_GOLD
	, PACKETTYPE_SCRIPT_TRANS_PXP
	, PACKETTYPE_SCRIPT_TRANS_PENYA
	, PACKETTYPE_CREATE_GUILDCLOAK
	, PACKETTYPE_LOCALPOSFROMIA
	, PACKETTYPE_CREATEANGEL
	, PACKETTYPE_SUMMONITEMUSE
	, PACKETTYPE_ANGELBUFF
	, PACKETTYPE_SNAPSHOT
	, PACKETTYPE_PLAYERBEHAVIOR
	, PACKETTYPE_PLAYERSETDESTOBJ
	, PACKETTYPE_QUERYGETPOS
	, PACKETTYPE_GETPOS
	, PACKETTYPE_REMOVEAPPLETTASKBAR
	, PACKETTYPE_ADDAPPLETTASKBAR
	, PACKETTYPE_ADDITEMTASKBAR
	, PACKETTYPE_REMOVEITEMTASKBAR
	, PACKETTYPE_SKILLTASKBAR
	, PACKETTYPE_MOVERDESTPOS
	, PACKETTYPE_ERRORPARTY
	, PACKETTYPE_ADDPARTYMEMBER
	, PACKETTYPE_REMOVEPARTYMEMBER
	, PACKETTYPE_ADDPLAYERPARTY
	, PACKETTYPE_REMOVEPLAYERPARTY
	, PACKETTYPE_MEMBERLEVEL
	, PACKETTYPE_SETLODELIGHT
	, PACKETTYPE_INC_JOB_LEVEL
	, PACKETTYPE_ADDEXPERIENCE
	, PACKETTYPE_SET_GROWTH_LEARNING_POINT
	, PACKETTYPE_SFX_HIT
	, PACKETTYPE_SETPOINTPARAM
	, PACKETTYPE_WHISPER
	, PACKETTYPE_ENDSKILLQUEUE
	, PACKETTYPE_CAPTION
	, PACKETTYPE_SAY
	, PACKETTYPE_SHOUT
	, PACKETTYPE_PLAYMUSIC
	, PACKETTYPE_PLAYSOUND
//	, PACKETTYPE_SUMMONPLAYER
//	, PACKETTYPE_TELEPORTPLAYER
	, PACKETTYPE_KILLPLAYER
	, PACKETTYPE_GETPLAYERADDR
	, PACKETTYPE_GETPLAYERCOUNT
	, PACKETTYPE_GETCOREPLAYER
	, PACKETTYPE_SYSTEM
	, PACKETTYPE_MODIFYMODE
	, PACKETTYPE_DEFINEDTEXT
	, PACKETTYPE_GMSAY
	, PACKETTYPE_CHANGEFACE
	, PACKETTYPE_NW_WANTED_GOLD
	, PACKETTYPE_MEMBERJOB
	, PACKETTYPE_MEMBERREQUEST
	, PACKETTYPE_MEMBERREQUESTCANCLE
	, PACKETTYPE_CHANGETROUP
	, PACKETTYPE_CHANPARTYNAME
	, PACKETTYPE_PARTYSKILLUSE
	, PACKETTYPE_SETPARTYMODE
	, PACKETTYPE_ADDPARTYEXP
	, PACKETTYPE_REMOVEPARTYPOINT
	, PACKETTYPE_PARTYCHANGEITEMMODE
	, PACKETTYPE_PARTYCHANGEEXPMODE
	, PACKETTYPE_SETPARTYEXP
	, PACKETTYPE_DUELREQUEST
	, PACKETTYPE_DUELYES
	, PACKETTYPE_DUELNO
	, PACKETTYPE_DUELPARTYREQUEST
	, PACKETTYPE_DUELPARTYYES
	, PACKETTYPE_DUELPARTYNO
	, PACKETTYPE_SETPARTYDUEL
	, PACKETTYPE_GUILD_BANK_UPDATE
	, PACKETTYPE_GUILD_BANK_WND_CLOSE
	, PACKETTYPE_GUILD_BANK_MOVEITEM
	, PACKETTYPE_OPENBANKWND
	, PACKETTYPE_CLOSEBANKWND
	, PACKETTYPE_PUTITEMBACK
	, PACKETTYPE_PUTGOLDBACK
	, PACKETTYPE_GETITEMBACK
	, PACKETTYPE_GETGOLDBACK
	, PACKETTYPE_MOVEBANKITEM
	, PACKETTYPE_CHANGEBANKPASS
	, PACKETTYPE_CONFIRMBANK
	, PACKETTYPE_PUTBACKTOBANK
	, PACKETTYPE_QUERYPLAYERLISTSTRING
	, PACKETTYPE_MOVERFOCOUS
	, PACKETTYPE_PARTYCHANGELEADER
	, PACKETTYPE_ALL_GUILD_DATA_NOTI
	, PACKETTYPE_GUILD
	, PACKETTYPE_CREATE_GUILD
	, PACKETTYPE_DESTROY_GUILD
	, PACKETTYPE_ADD_GUILD_MEMBER
	, PACKETTYPE_REMOVE_GUILD_MEMBER
	, PACKETTYPE_GUILD_INVITE
	, PACKETTYPE_IGNORE_GUILD_INVITE
	, PACKETTYPE_QUERYPLAYERSTRING
	, PACKETTYPE_GLOBAL_DATA
	, PACKETTYPE_GUILD_CHAT
	, PACKETTYPE_GUILD_MEMBER_LEVEL
	, PACKETTYPE_GUILD_BANK_QUERY
	, PACKETTYPE_GUILD_BANK
	, PACKETTYPE_PARTYCHAT
	, PACKETTYPE_BLOCK
	, PACKETTYPE_ADDFRIEND
	, PACKETTYPE_ADDFRIENDREQEST
	, PACKETTYPE_ADDFRIENDCANCEL
	, PACKETTYPE_GETFRIENDNAME
	, PACKETTYPE_GETFRIENDSTATE
	, PACKETTYPE_ADDFRIENDJOIN
	, PACKETTYPE_ADDFRIENDLOGOUT
	, PACKETTYPE_SETFRIENDSTATE
	, PACKETTYPE_FRIENDINTERCEPTSTATE
	, PACKETTYPE_FRIENDNOINTERCEPT
	, PACKETTYPE_REMOVEFRIEND
	, PACKETTYPE_ADDFRIENDNAMEREQEST
	, PACKETTYPE_ADDFRIENDNAMENOTFOUND
	, PACKETTYPE_REMOVEFRIENDSTATE
	, PACKETTYPE_ONEFRIEMDSTATE
	, PACKETTYPE_MONITOR_ID
	, PACKETTYPE_CONSOLE_COMMAND
	, PACKETTYPE_CONSOLE_OVERVIEW
	, PACKETTYPE_CONSOLE_FILEHEADER
	, PACKETTYPE_CONSOLE_FILEDATA
	, PACKETTYPE_CONSOLE_UPLOADACK
	, PACKETTYPE_CONSOLE_EXPAND
	, PACKETTYPE_CONSOLE_SYNCACK
	, PACKETTYPE_CONSOLE_EXPANDACK
	, PACKETTYPE_CONSOLE_OVERVIEW2
	, PACKETTYPE_PROCESS_CREATED
	, PACKETTYPE_PROCESS_TERMINATED
	, PACKETTYPE_MY_PROCESS
	, PACKETTYPE_CREATE_PROCESS
	, PACKETTYPE_TERMINATE_PROCESS
	, PACKETTYPE_TERMINATE_PROCESS_AND_QUIT
	, PACKETTYPE_PROCESS_MODE
	, PACKETTYPE_ADD_ACCOUNT
	, PACKETTYPE_REMOVE_ACCOUNT
	, PACKETTYPE_LOGOUT_ACCOUNT
	, PACKETTYPE_ROUTE
	, PACKETTYPE_QUERYGETDESTOBJ
	, PACKETTYPE_GETDESTOBJ
	, PACKETTYPE_GUILD_CLASS
	, PACKETTYPE_GUILD_NICKNAME
	, PACKETTYPE_GUILD_MEMBERTIME
	, PACKETTYPE_GUILD_MEMBERLOGOUT
	, PACKETTYPE_STATEMODE
	, PACKETTYPE_MODE
	, PACKETTYPE_CHEERING
	, PACKETTYPE_EVE_RECOMMEND
	, PACKETTYPE_SAVE_CONCURRENT_USER_NUMBER
	, PACKETTYPE_SAVE_CONCURRENT_FIELD_USER_NUMBER
	, PACKETTYPE_LOG_PLAY_CONNECT
	, PACKETTYPE_LOG_PLAY_DEATH
	, PACKETTYPE_LOG_LEVELUP
	, PACKETTYPE_DESTROY_PLAYER
	, PACKETTYPE_ERRORCODE
	, PACKETTYPE_PROCESS_CREATED2
	, PACKETTYPE_PROCESS_TERMINATED2
	, PACKETTYPE_MY_PROCESS2
	, PACKETTYPE_RENEWEVNET
	, PACKETTYPE_TAG
	, PACKETTYPE_SENDTAG
	, PACKETTYPE_INSERTTAG_RESULT
	, PACKETTYPE_PARTYLEVEL
	, PACKETTYPE_WC_GUILDLOGO
	, PACKETTYPE_WC_GUILDCONTRIBUTION
	, PACKETTYPE_WC_GUILDNOTICE
	, PACKETTYPE_CW_GUILDLOGO
	, PACKETTYPE_CW_GUILDCONTRIBUTION
	, PACKETTYPE_CW_GUILDNOTICE
	, PACKETTYPE_NW_GUILDLOGO
	, PACKETTYPE_NW_GUILDCONTRIBUTION
	, PACKETTYPE_NW_GUILDNOTICE
	, PACKETTYPE_FOCUSOBJ
	, PACKETTYPE_CALL_USPLOGGINGQUEST
	, PACKETTYPE_CD_GUILD_LOGO
	, PACKETTYPE_WD_GUILD_CONTRIBUTION
	, PACKETTYPE_CD_GUILD_NOTICE
	, PACKETTYPE_GUILD_BANK_WND
	, PACKETTYPE_UPDATE_GUILD_RANKING_END
	, PACKETTYPE_UPDATE_GUILD_RANKING_DB
	, PACKETTYPE_REQUEST_GUILD_RANKING
	, PACKETTYPE_WAR_DEAD
	, PACKETTYPE_WAR_END
	, PACKETTYPE_SURRENDER
	, PACKETTYPE_QUERY_TRUCE
	, PACKETTYPE_ACPT_TRUCE
	, PACKETTYPE_WAR_TIMEOUT
	, PACKETTYPE_WAR_MASTER_ABSENT
	, PACKETTYPE_SCHOOL_REPORT
	, PACKETTYPE_COMMERCIALELEM
	, PACKETTYPE_UPGRADEBASE
	, PACKETTYPE_ENCHANT
	, PACKETTYPE_PIERCING
	, PACKETTYPE_PIERCING_SIZE
	, PACKETTYPE_QUERYEQUIP
	, PACKETTYPE_QUERYEQUIPSETTING
	, PACHETTYPE_ITEMTRANSY
	, PACKETTYPE_RANDOMSCROLL
	, PACKETTYPE_REMVOE_ATTRIBUTE
	, PACKETTYPE_PUTITEMGUILDBANK
	, PACKETTYPE_GETITEMGUILDBANK
	, PACKETTYPE_GUILD_MSG_CONTROL
	, PACKETTYPE_GUILD_AUTHORITY
	, PACKETTYPE_GUILD_PENYA
	, PACKETTYPE_GUILD_DB_REALPENYA
	, PACKETTYPE_GUILD_GAMELOGIN
	, PACKETTYPE_GUILD_GAMEJOIN
	, PACKETTYPE_CHANGEGUILDJOBLEVEL
	, PACKETTYPE_GUILD_SETNAME
	, PACKETTYPE_GUILD_ERROR
	, PACKETTYPE_DECL_GUILD_WAR
	, PACKETTYPE_ACPT_GUILD_WAR
	, PACKETTYPE_NC_ADDVOTE
	, PACKETTYPE_NC_REMOVEVOTE
	, PACKETTYPE_NC_CLOSEVOTE
	, PACKETTYPE_NC_CASTVOTE
	, PACKETTYPE_CD_ADDVOTE
	, PACKETTYPE_CD_REMOVEVOTE
	, PACKETTYPE_CD_CLOSEVOTE
	, PACKETTYPE_CD_CASTVOTE
	, PACKETTYPE_DC_ADDVOTERESULT
	, PACKETTYPE_CW_ADDVOTERESULT
	, PACKETTYPE_CW_MODIFYVOTE
	, PACKETTYPE_UPDATE_GUILD_RANKING
	, PACKETTYPE_CHANGE_ATTRIBUTE
	, PACKETTYPE_UPDATEGUILDQUEST
	, PACKETTYPE_BUYING_INFO
	, PACKETTYPE_QUERYGUILDQUEST
	, PACKETTYPE_ENTERCHTTING
	, PACKETTYPE_CHATTING
	, PACKETTYPE_INSERTGUILDQUEST
	, PACKETTYPE_COMMONPLACE
	, PACKETTYPE_OPENCHATTINGROOM
	, PACKETTYPE_CLOSECHATTINGROOM
	, PACKETTYPE_DELETEGUILDQUEST
	, PACKETTYPE_JOIN_BATTLESERVER
	, PACKETTYPE_BASEGAMESETTING
	, PACKETTYPE_MONSTERRESPAWNSETTING
	, PACKETTYPE_MONSTERPROPGAMESETTING
	, PACKETTYPE_GAMEMASTER_CHATTING
	, PACKETTYPE_RELOAD_PROJECT
	, PACKETTYPE_CREATESFXOBJ
	, PACKETTYPE_RETURNSCROLL
	, PACKETTYPE_EVENT
	, PACKETTYPE_ADD_GUILDCOMBAT
	, PACKETTYPE_IN_GUILDCOMBAT
	, PACKETTYPE_OUT_GUILDCOMBAT
	, PACKETTYPE_JOIN_GUILDCOMBAT
	, PACKETTYPE_EVENT_GENERIC
	, PACKETTYPE_EVENT_FLAG
	, PACKETTYPE_CALL_XXX_MULTI_SERVER
	, PACKETTYPE_CTRL_COOLTIME_CANCEL
	, PACKETTYPE_LOG_EXPBOX
	, PACKETTYPE_TRAFIC_LOG
	, PACKETTYPE_KAWIBAWIBO_START
	, PACKETTYPE_KAWIBAWIBO_GETITEM
	, PACKETTYPE_REASSEMBLE_START
	, PACKETTYPE_REASSEMBLE_OPENWND
	, PACKETTYPE_ALPHABET_OPENWND
	, PACKETTYPE_ALPHABET_START
	, PACKETTYPE_FIVESYSTEM_OPENWND
	, PACKETTYPE_FIVESYSTEM_DESTROYWND
	, PACKETTYPE_FIVESYSTEM_BET
	, PACKETTYPE_FIVESYSTEM_START
	, PACKETTYPE_ULTIMATE_MAKEITEM
	, PACKETTYPE_ULTIMATE_MAKEGEM
	, PACKETTYPE_ULTIMATE_TRANSWEAPON
	, PACKETTYPE_ULTIMATE_ENCHANTWEAPON
	, PACKETTYPE_ULTIMATE_SETGEM
	, PACKETTYPE_ULTIMATE_REMOVEGEM
	, PACKETTYPE_EXCHANGE
	, PACKETTYPE_EVENTLUA_STATE
	, PACKETTYPE_EVENTLUA_CHANGED
	, PACKETTYPE_EVENTLUA_NEEDSTATE
	, PACKETTYPE_EVENTLUA_NOTICE
	, PACKETTYPE_LEGENDSKILLUP_START
	, PACKETTYPE_MODIFY_STATUS
	, PACKETTYPE_PET_RELEASE
	, PACKETTYPE_USE_PET_FEED
	, PACKETTYPE_PET_TAMER_MISTAKE
	, PACKETTYPE_PET_TAMER_MIRACLE
	, PACKETTYPE_FEED_POCKET_INACTIVE
	, PACKETTYPE_MAKE_PET_FEED
	, PACKETTYPE_CALL_USP_PET_LOG
	, PACKETTYPE_GC1TO1_TENDEROPENWND
	, PACKETTYPE_GC1TO1_TENDERVIEW
	, PACKETTYPE_GC1TO1_TENDER
	, PACKETTYPE_RESULT_GUILDCOMBAT
	, PACKETTYPE_GUILDCOMBAT_STATE
	, PACKETTYPE_SELECTPLAYER_GUILDCOMBAT
	, PACKETTYPE_REQUEST_STATUS
	, PACKETTYPE_REMOVEPARTY_GUILDCOMBAT
	, PACKETTYPE_ADDPARTY_GUILDCOMBAT
	, PACKETTYPE_SELECTMAP_GUILDCOMBAT
	, PACKETTYPE_START_GUILDCOMBAT
	, PACKETTYPE_GETPENYAGUILD_GUILDCOMBAT
	, PACKETTYPE_GETPENYAPLAYER_GUILDCOMBAT
	, PACKETTYPE_TELE_GUILDCOMBAT
	, PACKETTYPE_PLAYERPOINT_GUILDCOMBAT
	, PACKETTYPE_CONTINUE_GUILDCOMBAT
	, PACKETTYPE_SUMMON_FRIEND
	, PACKETTYPE_SUMMON_FRIEND_CONFIRM
	, PACKETTYPE_SUMMON_PARTY
	, PACKETTYPE_SUMMON_PARTY_CONFIRM
	, PACKETTYPE_SUMMON_FRIEND_CANCEL
	, PACKETTYPE_CHG_MASTER
	, PACKETTYPE_GLOBALGIFTBOX
	, PACKETTYPE_QUERYGLOBALGIFTBOX
	, PACKETTYPE_RESTOREGLOBALGIFTBOX
	, PACKETTYPE_QUERY_REMOVE_GUILD_BANK_TBL
	, PACKETTYPE_GC1TO1_TENDERCANCEL
	, PACKETTYPE_GC1TO1_OPEN
	, PACKETTYPE_GC1TO1_MEMBERLINEUPOPENWND
	, PACKETTYPE_GC1TO1_MEMBERLINEUP
	, PACKETTYPE_GC1TO1_TELEPORTTONPC
	, PACKETTYPE_GC1TO1_TELEPORTTOSTAGE
	, PACKETTYPE_GC1TO1_TENDERFAILED
	, PACKETTYPE_GC1TO1_STATETODB
	, PACKETTYPE_GC1TO1_TENDERTODB
	, PACKETTYPE_GC1TO1_TENDERTOSRVR
	, PACKETTYPE_GC1TO1_LINEUPTODB
	, PACKETTYPE_GC1TO1_WARPERSONTODB
	, PACKETTYPE_GC1TO1_WARGUILDTODB
	, PACKETTYPE_QUERY_START_COLLECTING
	, PACKETTYPE_QUERY_STOP_COLLECTING
	, PACKETTYPE_QUERY_PLAYER_DATA
	, PACKETTYPE_ALL_PLAYER_DATA
	, PACKETTYPE_ADD_PLAYER_DATA
	, PACKETTYPE_DELETE_PLAYER_DATA
	, PACKETTYPE_QUERY_PLAYER_DATA2
	, PACKETTYPE_UPDATE_PLAYER_DATA
	, PACKETTYPE_PIERCINGREMOVE
	, PACKETTYPE_GUILDLOG_VIEW
	, PACKETTYPE_SEALCHAR_REQ
	, PACKETTYPE_SEALCHARCONM_REQ
	, PACKETTYPE_NPC_BUFF
	, PACKETTYPE_SEALCHARGET_REQ
	, PACKETTYPE_SEALCHARSET_REQ
	, PACKETTYPE_ADD_MESSENGER
	, PACKETTYPE_DELETE_MESSENGER
	, PACKETTYPE_UPDATE_MESSENGER
	, PACKETTYPE_ERROR_STRING
	, PACKETTYPE_TAX_SET_SECRETROOM_WINNER
	, PACKETTYPE_TAX_SET_LORD
	, PACKETTYPE_TAX_SET_TAXRATE
	, PACKETTYPE_TAX_ADDSALESTAX
	, PACKETTYPE_TAX_ADDPURCHASEAX
	, PACKETTYPE_TAX_ADDTAX
	, PACKETTYPE_TAX_APPLY_TAXRATE_NOW
	, PACKETTYPE_HEAVENTOWER_TELEPORT
	, PACKETTYPE_RAINBOWRACE_PREVRANKING_OPENWND
	, PACKETTYPE_RAINBOWRACE_APPLICATION_OPENWND
	, PACKETTYPE_RAINBOWRACE_APPLICATION
	, PACKETTYPE_RAINBOWRACE_MINIGAME_PACKET
	, PACKETTYPE_RAINBOWRACE_REQ_FINISH
	, PACKETTYPE_RAINBOWRACE_LOADDBTOWORLD
	, PACKETTYPE_RAINBOWRACE_APPTODB
	, PACKETTYPE_RAINBOWRACE_FAILEDTODB
	, PACKETTYPE_RAINBOWRACE_RANKINGTODB
	, PACKETTYPE_HOUSING_LOADINFO
	, PACKETTYPE_HOUSING_FURNITURELIST
	, PACKETTYPE_HOUSING_SETUPFURNITURE
	, PACKETTYPE_HOUSING_DBFAILED
	, PACKETTYPE_HOUSING_VISITROOM
	, PACKETTYPE_HOUSING_SETVISITALLOW
	, PACKETTYPE_HOUSING_REQVISITABLELIST
	, PACKETTYPE_HOUSING_GOOUT
	, PACKETTYPE_HOUSING_GM_REMOVEALL
	, PACKETTYPE_DO_USE_ITEM_TARGET
	, PACKETTYPE_REMOVE_ITEM_LEVEL_DOWN
	, PACKETTYPE_AVAIL_POCKET
	, PACKETTYPE_MOVE_ITEM_POCKET
	, PACKETTYPE_AWAKENING
	, PACKETTYPE_QUE_PETRESURRECTION
	, PACKETTYPE_BLESSEDNESS_CANCEL
	, PACKETTYPE_LOGOUT
	, PACKETTYPE_ARENA_ENTER
	, PACKETTYPE_ARENA_EXIT
	, PACKETTYPE_SECRETROOM_TENDER
	, PACKETTYPE_SECRETROOM_LINEUPMEMBER
	, PACKETTYPE_SECRETROOM_TENDEROPENWND
	, PACKETTYPE_SECRETROOM_LINEUPOPENWND
	, PACKETTYPE_SECRETROOM_ENTRANCE
	, PACKETTYPE_SECRETROOM_TELEPORTTONPC
	, PACKETTYPE_SECRETROOM_TENDERVIEW
	, PACKETTYPE_SECRETROOM_TENDERCANCELRETURN
	, PACKETTYPE_SECRETROOM_TENDER_INSERTTODB
	, PACKETTYPE_SECRETROOM_TENDER_UPDATETODB
	, PACKETTYPE_SECRETROOM_LINEUP_INSERTTODB
	, PACKETTYPE_SECRETROOM_INFO_CLEAR
	, PACKETTYPE_SECRETROOM_TENDERINFO_TO_WSERVER
	, PACKETTYPE_SECRETROOM_CLOSED
	, PACKETTYPE_SECRETROOM_TELEPORTTODUNGEON
	, PACKETTYPE_TAX_ALLINFO
	, PACKETTYPE_HONOR_LIST_REQ
	, PACKETTYPE_HONOR_CHANGE_REQ
	, PACKETTYPE_LOG_GETHONORTIME
	, PACKETTYPE_QUESTHELPER_REQNPCPOS
	, PACKETTYPE_FUNNYCOIN_REQ_USE
	, PACKETTYPE_FUNNYCOIN_ACK_USE
	, PACKETTYPE_PCBANG_SETAPPLY
	, PACKETTYPE_TIMELIMIT_INFO
	, PACKETTYPE_TIMELIMIT_UPDATE
	, PACKETTYPE_TIMELIMIT_RESET
	, PACKETTYPE_SMELT_SAFETY
	, PACKETTYPE_ELECTION_ADD_DEPOSIT
	, PACKETTYPE_ELECTION_SET_PLEDGE
	, PACKETTYPE_ELECTION_INC_VOTE
	, PACKETTYPE_ELECTION_BEGIN_CANDIDACY
	, PACKETTYPE_ELECTION_BEGIN_VOTE
	, PACKETTYPE_ELECTION_END_VOTE
	, PACKETTYPE_ELECTION_PROCESS
	, PACKETTYPE_LORD
	, PACKETTYPE_L_EVENT_CREATE
	, PACKETTYPE_LORD_SKILL_USE
	, PACKETTYPE_L_EVENT_INITIALIZE
	, PACKETTYPE_QUIZ_STATE
	, PACKETTYPE_QUIZ_NOTICE
	, PACKETTYPE_QUIZ_ENTRANCE
	, PACKETTYPE_QUIZ_TELEPORT
	, PACKETTYPE_QUIZ_LOADQUIZ
	, PACKETTYPE_QUIZ_PRIZEITEM
	, PACKETTYPE_QUIZ_SELECT
	, PACKETTYPE_QUIZ_OPEN
	, PACKETTYPE_VISPET_REMOVEVIS
	, PACKETTYPE_VISPET_SWAPVIS
	, PACKETTYPE_GUILDHOUSE_LOAD
	, PACKETTYPE_GUILDHOUSE_BUY
	, PACKETTYPE_GUILDHOUSE_REMOVE
	, PACKETTYPE_GUILDHOUSE_PACKET
	, PACKETTYPE_GUILDHOUSE_ALLINFO
	, PACKETTYPE_GUILDHOSUE_RESTPOINT
	, PACKETTYPE_GUILDHOUSE_ENTER
	, PACKETTYPE_GUILDHOUSE_GOOUT
	, PACKETTYPE_GUILDFURNITURE_LOG
	, PACKETTYPE_TELEPORTER
	, PACKETTYPE_LORD_SKILL_TICK
	, PACKETTYPE_L_EVENT_TICK
	, PACKETTYPE_TRANSFORM_ITEM
	, PACKETTYPE_TUTORIAL_STATE
	, PACKETTYPE_PICKUP_PET_AWAKENING_CANCEL
	, PACKETTYPE_OPTION_ENABLE_RENDER_MASK
	, PACKETTYPE_DO_USE_ITEM_INPUT
	, PACKETTYPE_CLEAR_PET_NAME
	, PACKETTYPE_PROPOSE
	, PACKETTYPE_REFUSE
	, PACKETTYPE_COUPLE
	, PACKETTYPE_DECOUPLE
	, PACKETTYPE_ALL_COUPLES
	, PACKETTYPE_CLEAR_PROPOSE
	, PACKETTYPE_ADD_COUPLE_EXPERIENCE
	, PACKETTYPE_INSTANCEDUNGEON_ALLINFO
	, PACKETTYPE_INSTANCEDUNGEON_CREATE
	, PACKETTYPE_INSTANCEDUNGEON_DESTROY
	, PACKETTYPE_INSTANCEDUNGEON_SETCOOLTIME
	, PACKETTYPE_INSTANCEDUNGEON_DELETECOOLTIME
	, PACKETTYPE_INSTANCEDUNGEON_LOG
	, PACKETTYPE_MAP_KEY
	, PACKETTYPE_QUIZ_CHANGED
	, PACKETTYPE_QUEST_CHECK
	, PACKETTYPE_CAMPUS_ALL
	, PACKETTYPE_CAMPUS_INVITE
	, PACKETTYPE_CAMPUS_ACCEPT
	, PACKETTYPE_CAMPUS_REFUSE
	, PACKETTYPE_CAMPUS_ADD_MEMBER
	, PACKETTYPE_CAMPUS_REMOVE_MEMBER
	, PACKETTYPE_CAMPUS_UPDATE_POINT
	, PACKETTYPE_LOGIN_PROTECT_NUMPAD
	, PACKETTYPE_LOGIN_PROTECT_CERT
	, PACKETTYPE_ERROR_LOG_TO_DB
	, PACKETTYPE_COLLECTION_CERTIFY
	, PACKETTYPE_ITEM_SELECT_AWAKENING_VALUE
	, PACKETTYPE_GUILDHOUSE_TENDER_MAINWND
	, PACKETTYPE_GUILDHOUSE_TENDER_INFOWND
	, PACKETTYPE_GUILDHOUSE_TENDER_INFO
	, PACKETTYPE_GUILDHOUSE_TENDER_JOIN
	, PACKETTYPE_GUILDHOUSE_TENDER_STATE
	, PACKETTYPE_GUILDHOUSE_GRADE_UPDATE
	, PACKETTYPE_GUILDHOUSE_LEVEL_UPDATE
	, PACKETTYPE_GUILDHOUSE_EXPIRED
	, PACKETTYPE_QUERYMAILBOX_REQ
	, PACKETTYPE_QUERYMAILBOX_COUNT
	, PACKETTYPE_COUPON_ITEM_NUMBER
	, PACKETTYPE_ITEM_LINK_INFO
	, PACKETTYPE_BARUNA16_OPER_EXTRACT
	, PACKETTYPE_BARUNA16_OPER_CREATE
	, PACKETTYPE_BARUNA16_CID_CREATE
	, PACKETTYPE_BARUNA16_CIDPIECE_UPGRADE
	, PACKETTYPE_BARUNA16_OPERCID_CREATE
	, PACKETTYPE_SERIALNUMBER_REQ				// 할당 가능한 시리얼넘버 요청
	, PACKETTYPE_SERIALNUMBER_ACK				// 할당 가능한 시리얼넘버
	, PACKETTYPE_BASEGAMESETTING_REQ
	, PACKETTYPE_GUILDHOUSE_INFOWND
	, PACKETTYPE_GUILDHOUSE_COMMENT
	, PACKETTYPE_BUY_SHOPPING_BASKET
	, PACKETTYPE_RESET_BIND
#ifdef __APP_TELEPORTER
, PACKETTYPE_APP_TELEPORT	
#endif
#ifdef __TIMER
, PACKETTYPE_TIMER
#endif // __TIMER

	// CS
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_GET_INFO_REQ			
	//, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_GET_INFO_ACK

	// W->DB
    , PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_REQ		//W->DB
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_ACK		//DB->W
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_GET_CONTRIBUTED_REQ			
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_GET_CONTRIBUTED_ACK
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_GET_RANKING_REQ
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_GET_RANKING_ACK
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_TRY_REWARD_ITEM_REQ
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_TRY_REWARD_ITEM_ACK
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_TRY_WRITE_ITEM_REWARD_INFO_REQ		//W->DB
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_TRY_WRITE_ITEM_REWARD_INFO_ACK		//DB->W
	, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_SPEC_NOTI


	//, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_REWARD_ITEM_REQ		//W->DB
	// DB->W->C
	//, PACKETTYPE_COOPERATIVE_CONTRIBUTIONS_REWARD_ITEM_ACK		//DB->W->C

	// CS
	, PACKETTYPE_COLOSSEUM_ENTER_REQ				//CS 콜로세움 입장
	, PACKETTYPE_COLOSSEUM_LEAVE_NOTI				//CS 콜로세움 나가기
	, PACKETTYPE_COLOSSEUM_RETRY_REQ				//CS 재시도

	, PACKETTYPE_COLOSSEUM_AUTO_INVITE_ACK			//CS 자동 초대 응답
	, PACKETTYPE_COLOSSEUM_FORCE_START				//CS 시작 버튼 눌러 시작
	, PACKETTYPE_COLOSSEUM_REGIST_ADDITIONAL_REAL_MONSTER_RATE_ITEM	//CS 리얼 몬스터 출연 확률 올려주는 아이템 등록
	, PACKETTYPE_COLOSSEUM_UNREGIST_ADDITIONAL_REAL_MONSTER_RATE_ITEM	//CS 리얼 몬스터 출연 확률 올려주는 아이템 등록해제
	, PACKETTYPE_COLOSSEUM_GET_RANKING_INFO			//CS WDB 콜로세움 랭킹 정보 가져오기

	// W->DB
	, PACKETTYPE_RECORD_DUNGEON_PLAY_INFO			//던전 플레이정보 DB 기록
	

	, PACKETTYPE_TELEPORT_MAP_TO_POINT_REQ			// 텔레포트 요청
	, PACKETTYPE_TELEPORT_MAP_ADD_MY_POINT_REQ		// 텔레포트 지도 아이템 현재 위치 등록 요청
	, PACKETTYPE_TELEPORT_MAP_CHG_POINT_NAME_REQ	// 텔레포트 지도 아이템 등록 위치 이름 수정 요청
	, PACKETTYPE_TELEPORT_MAP_DEL_POINT_REQ			// 텔레포트 지도 아이템 등록 위치 삭제 요청
	, PACKETTYPE_TELEPORT_MAP_DEL_ALL_POINT_REQ		// 텔레포트 지도 아이템 등록 위치 모두 삭제 요청

	, PACKETTYPE_TELEPORT_MAP_POINT_LIST_NOTI		// 텔레포트 지도 유저 등록 리스트(DatabaseServer->WorldServer)
	, PACKETTYPE_TELEPORT_MAP_ADD_POINT_NOTI		// 텔레포트 지도 유저 등록 통보(WorldServer->DatabaseServer)
	, PACKETTYPE_TELEPORT_MAP_CHG_POINT_NAME_NOTI	// 텔레포트 지도 유저 등록 위치 이름 수정 통보(WorldServer->DatabaseServer)
	, PACKETTYPE_TELEPORT_MAP_DEL_POINT_NOTI		// 텔레포트 지도 유저 등록 위치 삭제 통보(WorldServer->DatabaseServer)


	// 이벤트용 아레나(참가 선수)
	, PACKETTYPE_EVENT_ARENA_MOVE_BATTLE_WAIT_NOTI			// NPC 이용 선수대기 지역 이동 요청


	// 이벤트용 아레나(관리자)
	, PACKETTYPE_EVENT_ARENA_MANAGE_SET_TONEMENT_NOTI		// 토너먼트 설정 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_SET_RED_TEAM_NOTI		// 레드팀 설정 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_SET_BLUE_TEAM_NOTI		// 블루팀 설정 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_CALL_PLAYERS_NOTI		// 선수소환 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_JOIN_PLAYERS_NOTI		// 선수입장 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_BATTLE_START_NOTI		// 전투 시작 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_GAME_END_NOTI			// 게임 종료 통지
	, PACKETTYPE_EVENT_ARENA_MANAGE_GAME_STOP_NOTI			// 게임 중지 통지


	// XTRAP
	, PACKETTYPE_XTRAP_COMMAND_REQUEST
	, PACKETTYPE_XTRAP_COMMAND_RESPONSE


	// 아이템 업그레이드
	, PACKETTYPE_ITEM_UPGRADE_GENERAL_ENCHANT_REQ				// 일반 제련 요청
	, PACKETTYPE_ITEM_UPGRADE_ATTRIBUTE_ENCHANT_REQ				// 속성 제련 요청
	, PACKETTYPE_ITEM_UPGRADE_ATTRIBUTE_CHANGE_REQ				// 속성 변경 요청
	, PACKETTYPE_ITEM_UPGRADE_ATTRIBUTE_REMOVE_REQ				// 속성 제거 요청
	, PACKETTYPE_ITEM_UPGRADE_PIERCING_INCREASE_SIZE_REQ		// 피어싱 소켓 사이즈 증가 요청
	, PACKETTYPE_ITEM_UPGRADE_PIERCING_INSERT_ITEM_REQ			// 피어싱 아이템 넣기 요청
	, PACKETTYPE_ITEM_UPGRADE_PIERCING_REMOVE_ITEM_REQ			// 피어싱 아이템 빼기 요청
	, PACKETTYPE_ITEM_UPGRADE_RANDOM_OPTION_GENERATE_REQ		// 각성 옵션 부여 요청
	, PACKETTYPE_ITEM_UPGRADE_RANDOM_OPTION_INITIALIZE_REQ		// 각성 옵션 제거 요청
	, PACKETTYPE_ITEM_UPGRADE_EQUIP_LEVEL_DECREASE_REQ			// 착용 레벨 하락 요청
	, PACKETTYPE_ITEM_UPGRADE_EQUIP_LEVEL_INITIALIZE_REQ		// 착용 레벨 하락 제거 요청
	, PACKETTYPE_ITEM_UPGRADE_COMBINE_REQ						// 아이템 합성 요청
	, PACKETTYPE_ITEM_UPGRADE_COMBINE_INITIALIZE_DATA_REQ		// 아이템 합성 취소 데이터 요청
	, PACKETTYPE_ITEM_UPGRADE_COMBINE_INITIALIZE_REQ			// 아이템 합성 취소 요청
	, PACKETTYPE_ITEM_UPGRADE_LOOKS_CHANGE_REQ					// 아이템 외형 변경 요청
	, PACKETTYPE_ITEM_UPGRADE_LOOKS_INITIALIZE_REQ				// 아이템 외형 변경 취소 요청


	, PACKETTYPE_ITEM_MERGE_REQ					// 아이템 합성 요청


	, PACKETTYPE_CHARGE_ZONE_TICKET_ENTERANCE_REQ				// 유료 지역 입장 요청
	, PACKETTYPE_CHARGE_ZONE_TICKET_LEAVE_REQ					// 유료 지역 퇴장 요청

	, PACKETTYPE_TREASURE_CHEST_OPEN_BY_KEY_REQ					// 보물 상자 오픈 요청

	, PACKETTYPE_BROADCAST_MESSAGE				// 전체 알림 메시지


	// 거래 중개 C <-> S
	, PACKETTYPE_CONSIGNMENT_SALE_USER_INFO_REQ						// 유저 정보
	, PACKETTYPE_CONSIGNMENT_SALE_REGIST_REQ						// 등록
	, PACKETTYPE_CONSIGNMENT_SALE_CANCEL_REGISTED_REQ				// 등록 취소
	, PACKETTYPE_CONSIGNMENT_SALE_REGISTED_INFO_LIST_REQ			// 등록 리스트
	, PACKETTYPE_CONSIGNMENT_SALE_BUY_ITEM_REQ						// 구매
	, PACKETTYPE_CONSIGNMENT_SALE_COLLECT_SALE_GOLD_REQ				// 정산 판매 골드
	, PACKETTYPE_CONSIGNMENT_SALE_SEARCH_REQ						// 검색
	, PACKETTYPE_CONSIGNMENT_SALE_COLLECT_SALE_GOLD_INFO_LIST_REQ	// 정산 판매 골드 정보
	, PACKETTYPE_CONSIGNMENT_SALE_CALC_TAX_REQ						// 세금 정보 얻기


	, PACKETTYPE_CONSIGNMENT_SALE_USER_INFO_ACK						// 유저 정보
	, PACKETTYPE_CONSIGNMENT_SALE_SELL_ITEM_NOTI					
	, PACKETTYPE_CONSIGNMENT_SALE_REGIST_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_REGISTED_INFO_LIST_ACK					
	, PACKETTYPE_CONSIGNMENT_SALE_CANCEL_REGISTED_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_BUY_ITEM_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_COLLECT_SALE_GOLD_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_SEARCH_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_COLLECT_SALE_GOLD_INFO_LIST_ACK

	// 거래 중개 W <-> DB
	, PACKETTYPE_CONSIGNMENT_SALE_CHECK_REGISTED_COUNT_REQ
	, PACKETTYPE_CONSIGNMENT_SALE_CHECK_REGISTED_COUNT_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_GET_REGISTED_COUNT_REQ
	, PACKETTYPE_CONSIGNMENT_SALE_GET_REGISTED_COUNT_ACK
	, PACKETTYPE_CONSIGNMENT_SALE_GET_PRICE_REQ						// 가격 가져오기 
	, PACKETTYPE_CONSIGNMENT_SALE_GET_PRICE_ACK						// 가격 가져오기
	, PACKETTYPE_CONSIGNMENT_SALE_CLEAR_RESERVE_INFO_NOTI				// 예약 정보 초기화

	, PACKETTYPE_CHARACTER_SERVER_TRANSFORM_TO_OTHER_SERVER_REQ		// 캐릭터 서버군 이동 요청
	, PACKETTYPE_CHARACTER_SERVER_TRANSFORM_TO_OTHSER_SERVER_NOTI
	, PACKETTYPE_CHARACTER_SERVER_TRANSFORM_TO_OTHSER_SERVER_ACK
	, PACKETTYPE_JOIN_IN_SHUTDOWN_RULE									//셧다운 룰에 의한 종료

	//, PACKETTYPE_DO_APPLY_TARGET_ITEM										//아이템 적용

	, PACKETTYPE_LOG_TRADE											// 개인간 거래 로그
	, PACKETTYPE_LOG_ITEM											// 일반적인 아이템 로그
	, PACKETTYPE_TELEPORT_TO_NPC									// NPC 메뉴를 통한 텔레포트

	, PACKETTYPE_UPDATE_TAX_RATE									// GM명령어를 통한 세율 변경

	, PACKETTYPE_ITEM_UPGRADE_RANDOM_OPTION_GENERATE_RETRY_REQ		// 각성 옵션 부여 재시도 요청

	, PACKETTYPE_ITEM_UPGRADE_RANDOM_OPTION_SYNC_REQ				// 각성 옵션 싱크 요청
	
	, PACKETTYPE_SET_PARTY_EFFECT_MODE_NOTI

	, PACKETTYPE_MADRIGAL_GIFT_ITEM_RECV_REQ

	, PACKETTYPE_REFRESH_PARTY_EFFECT_MODE_NOTI

	, PACKETTYPE_FLYFF_PIECE_EXCHANGE_LIST_REQ
	, PACKETTYPE_EXCHANGE_FLYFF_PIECE_ITEM_REQ

	, PACKETTYPE_FORCE_SET_PARTY_SKILL_TIME

	, PACKETTYPE_START_FLYFF_PIECE_BURNING_MODE
	, PACKETTYPE_END_FLYFF_PIECE_BURNING_MODE

	, PACKETTYPE_INSTANCEDUNGEON_RESET_COOLTIME

	, PACKETTYPE_GUILD_BANK_QUERY_FAIL_ACK

	, PACKETTYPE_ITEM_EXCHANGE_REQ

	, PACKETTYPE_GUILD_BANK_INPUT_ITEM_REQ
	, PACKETTYPE_GUILD_BANK_INPUT_ITEM_ACK
	, PACKETTYPE_GUILD_BANK_OUTPUT_ITEM_REQ
	, PACKETTYPE_GUILD_BANK_OUTPUT_ITEM_ACK

	, PACKETTYPE_GUILD_BANK_INPUT_GOLD_REQ
	, PACKETTYPE_GUILD_BANK_INPUT_GOLD_ACK
	, PACKETTYPE_GUILD_BANK_OUTPUT_GOLD_REQ
	, PACKETTYPE_GUILD_BANK_OUTPUT_GOLD_ACK
	
	, PACKETTYPE_SEASON_EFFECT
	, PACKETTYPE_AUTHQUERY_VER30
	, PACKETTYPE_ERROR_CODE_STRING
	, PACKETTYPE_PARTYNAME
	, PACKETTYPE_ADDPARTYNAME
	, PACKETTYPE_LOG_SERVER_DEATH
	, PACKETTYPE_LOG_UNIQUEITEM
	, PACKETTYPE_LOG_QUEST
	, PACKETTYPE_LOG_GAMEMASTER_CHAT
	, PACKETTYPE_LOG_PK_PVP
	, PACKETTYPE_LOG_SCHOOL
	, PACKETTYPE_PREVENT_LOGIN
	, PACKETTYPE_FREQUENCY_LOG
#ifdef INVENTORY_ITEM_ALIGN
	, PACKETTYPE_ALIGNITEM
#endif	// INVENTORY_ITEM_ALIGN
#ifdef PAT_LOOTOPTION
	, PACKETTYPE_PETLOOTTYPE_REQ
#endif // PAT_LOOTOPTION
#ifdef BARUNA_ULTIMATE_UPDATE
	, PACKETTYPE_BARUNAULTIMATE_TRANSWEAPON_REQ
#endif	// BARUNA_ULTIMATE_UPDATE
#ifdef CARD_UPGRADE_SYSTEM
	, PACKETTYPE_ITEM_UPGRADE_CARD_REQ
#endif	// CARD_UPGRADE_SYSTEM
#ifdef	KEYBOARD_SET
	, PACKETTYPE_KEYBOARDMODESETTING
#endif	// KEYBOARD_SET 
#ifdef COSTUME_UPGRADE_ENHANCEMENT_GEM
	, PACKETTYPE_ITEM_UPGRADE_SETGEM_REQ
	, PACKETTYPE_ITEM_UPGRADE_REMOVEGEM_REQ
#endif
#ifdef COSTUME_UPGRADE_MIX
	, PACKETTYPE_ITEM_UPGRADE_MIX_REQ
#endif
	, PACKETTYPE_OPTION_ENABLE_RENDER_COSTUME
#ifdef __ZCK_ARME_RARE
	, PACKETTYPE_ZCK_ARME_RARE
#endif // __ZCK_ARME_RARE
#ifdef __ZCK_AMELIORATION_ADMIN
	, PACKETTYPE_SEND_UPGRADE
#endif // __ZCK_AMELIORATION_ADMIN
#ifdef __ZCK_WORLD_BOSS
	, PACKETTYPE_WORLDBOSS_TELEPORT
#endif // __ZCK_WORLD_BOSS
#ifdef __ZCK_INVASIONS
	, PACKETTYPE_ZCK_INVASIONS_REFRESH
#endif // __ZCK_INVASIONS
#ifdef __ZCK_WIKI
	, PACKETTYPE_WIKI_CREATE
#endif // __ZCK_WIKI
#ifdef __ZCK_TELEPORTEUR
	, PACKETTYPE_ZCK_TELEPORTEUR
#endif // __ZCK_TELEPORTEUR
#ifdef __ZCK_RECORD
	, PACKETTYPE_ZCK_RECORD_REQUEST
#endif // __ZCK_RECORD
};

// END PACKETTYPE
//////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////////////////////////
// BEGIN SNAPSHOTTYPE

enum	FL_SNAPSHOTTYPE { 
	SNAPSHOTTYPE_DEFAULT = DEFAULT_SNAPSHOTTYPE
	
	, SNAPSHOTTYPE_TRADECANCEL
	, SNAPSHOTTYPE_TRADECONSENT
	, SNAPSHOTTYPE_SYNCITEM
	, SNAPSHOTTYPE_SETPOSANGLE
	, SNAPSHOTTYPE_CREATESFXOBJ
	, SNAPSHOTTYPE_SETPOS
	, SNAPSHOTTYPE_SETLEVEL
	, SNAPSHOTTYPE_SETEXPERIENCE
	, SNAPSHOTTYPE_DAMAGE
	, SNAPSHOTTYPE_OPENSHOPWND
	, SNAPSHOTTYPE_CHAT
	, SNAPSHOTTYPE_ACTMSG
	, SNAPSHOTTYPE_CREATEITEM
	, SNAPSHOTTYPE_MOVEITEM
	, SNAPSHOTTYPE_TRADEPUTERROR
	, SNAPSHOTTYPE_DOEQUIP
	, SNAPSHOTTYPE_TRADE
	, SNAPSHOTTYPE_TRADEPUT
	, SNAPSHOTTYPE_TRADEPULL
	, SNAPSHOTTYPE_TRADEOK
	, SNAPSHOTTYPE_VENDOR
	, SNAPSHOTTYPE_UPDATE_VENDOR
	, SNAPSHOTTYPE_UPDATE_MOVER
	, SNAPSHOTTYPE_UPDATE_ITEM
	, SNAPSHOTTYPE_RUNSCRIPTFUNC
	, SNAPSHOTTYPE_SETSKILLLEVEL
	, SNAPSHOTTYPE_SETFXP
	, SNAPSHOTTYPE_SETFLIGHTLEVEL
	, SNAPSHOTTYPE_TRADELASTCONFIRM
	, SNAPSHOTTYPE_TRADELASTCONFIRMOK
	, SNAPSHOTTYPE_SCHOOL_REPORT
	, SNAPSHOTTYPE_GAMERATE
	, SNAPSHOTTYPE_EVENTMESSAGE
	, SNAPSHOTTYPE_DUELREQUEST
	, SNAPSHOTTYPE_DUELSTART
	, SNAPSHOTTYPE_USESKILL
	, SNAPSHOTTYPE_CLEAR_USESKILL
	, SNAPSHOTTYPE_QUERYGETPOS
	, SNAPSHOTTYPE_SETDESTPARAM
	, SNAPSHOTTYPE_RESETDESTPARAM
	, SNAPSHOTTYPE_SETPOINTPARAM
	, SNAPSHOTTYPE_GETPOS
	, SNAPSHOTTYPE_TRADEPUTGOLD
	, SNAPSHOTTYPE_TRADECLEARGOLD
	, SNAPSHOTTYPE_CONFIRMTRADE
	, SNAPSHOTTYPE_CONFIRMTRADECANCEL
	, SNAPSHOTTYPE_DUELNO
	, SNAPSHOTTYPE_DUELCANCEL
	, SNAPSHOTTYPE_DUELPARTYREQUEST
	, SNAPSHOTTYPE_DUELPARTYSTART
	, SNAPSHOTTYPE_DUELPARTYNO
	, SNAPSHOTTYPE_DUELPARTYCANCEL
	, SNAPSHOTTYPE_DUELPARTYRESULT
	, SNAPSHOTTYPE_SETSCALE
	, SNAPSHOTTYPE_PVENDOR_ITEM
	, SNAPSHOTTYPE_PVENDOR_ITEM_NUM
	, SNAPSHOTTYPE_UNREGISTER_PVENDOR_ITEM
	, SNAPSHOTTYPE_SET_HAIR
	, SNAPSHOTTYPE_QUERYGETDESTOBJ
	, SNAPSHOTTYPE_GETDESTOBJ
	, SNAPSHOTTYPE_SETFUEL
	, SNAPSHOTTYPE_SETSKILLSTATE
	, SNAPSHOTTYPE_CHANGEFACE
	, SNAPSHOTTYPE_MONSTERPROP
	, SNAPSHOTTYPE_REMOVEQUEST
	, SNAPSHOTTYPE_MOVERFOCUS
	, SNAPSHOTTYPE_PARTYMAPINFO
	, SNAPSHOTTYPE_SM_MODE_ALL
	, SNAPSHOTTYPE_SM_MODE
	, SNAPSHOTTYPE_SETFAME
	, SNAPSHOTTYPE_CORRREQ
	, SNAPSHOTTYPE_PVENDOR_OPEN
	, SNAPSHOTTYPE_PVENDOR_CLOSE
	, SNAPSHOTTYPE_REGISTER_PVENDOR_ITEM
	, SNAPSHOTTYPE_GMCHAT
	, SNAPSHOTTYPE_PUTITEMBANK
	, SNAPSHOTTYPE_GETITEMBANK
	, SNAPSHOTTYPE_PUTGOLDBANK
	, SNAPSHOTTYPE_MOVEBANKITEM
	, SNAPSHOTTYPE_UPDATE_BANKITEM
	, SNAPSHOTTYPE_BANKISFULL
	, SNAPSHOTTYPE_BANKWINDOW
	, SNAPSHOTTYPE_CHANGEBANKPASS
	, SNAPSHOTTYPE_CONFIRMBANKPASS
	, SNAPSHOTTYPE_SETSTUN
	, SNAPSHOTTYPE_SETPOISON
	, SNAPSHOTTYPE_SETDARK
	, SNAPSHOTTYPE_SENDACTMSG
	, SNAPSHOTTYPE_ADDFRIENDREQEST
	, SNAPSHOTTYPE_ADDFRIENDCANCEL
	, SNAPSHOTTYPE_ADDGETFRIENDNAME
	, SNAPSHOTTYPE_ADDFRIENDGAMEJOIN
	, SNAPSHOTTYPE_REMOVEFRIEND
	, SNAPSHOTTYPE_ADDFRIENDERROR
	, SNAPSHOTTYPE_ADDFRIENDCHANGEJOB
	, SNAPSHOTTYPE_ADDGAMEJOIN
	, SNAPSHOTTYPE_ADDPARTYCHANGELEADER
	, SNAPSHOTTYPE_SET_WAR
	, SNAPSHOTTYPE_CHATTING
	, SNAPSHOTTYPE_INITSKILLPOINT
	, SNAPSHOTTYPE_DOUSESKILLPOINT
	, SNAPSHOTTYPE_COMMONPlACE
	, SNAPSHOTTYPE_END_RECOVERMODE
	, SNAPSHOTTYPE_WANTED_INFO
	, SNAPSHOTTYPE_ERRORPARTY
	, SNAPSHOTTYPE_RESISTSMMODE
	, SNAPSHOTTYPE_COMMERCIALELEM
	, SNAPSHOTTYPE_PUSHPOWER
	, SNAPSHOTTYPE_PK_RELATION
	, SNAPSHOTTYPE_SETDUEL
	, SNAPSHOTTYPE_DUELCOUNT
	, SNAPSHOTTYPE_ADDPARTYNAME
	, SNAPSHOTTYPE_PARTYCHAT
	, SNAPSHOTTYPE_SETSTATE
	, SNAPSHOTTYPE_CMDSETSKILLLEVEL
	, SNAPSHOTTYPE_ACTIVESKILL
	, SNAPSHOTTYPE_RESETBUFFSKILL
	, SNAPSHOTTYPE_ADDFRIEND
	, SNAPSHOTTYPE_PARTYMEMBER
	, SNAPSHOTTYPE_PARTYREQEST
	, SNAPSHOTTYPE_PARTYREQESTCANCEL
	, SNAPSHOTTYPE_PARTYEXP
	, SNAPSHOTTYPE_PARTYMEMBERJOB
	, SNAPSHOTTYPE_PARTYMEMBERLEVEL
	, SNAPSHOTTYPE_PARTYCHANGETROUP
	, SNAPSHOTTYPE_PARTYCHANGENAME
	, SNAPSHOTTYPE_PARTYSKILL_CALL
	, SNAPSHOTTYPE_PARTYSKILL_BLITZ
	, SNAPSHOTTYPE_PARTYSKILL_RETREAT
	, SNAPSHOTTYPE_SETPARTYMODE
	, SNAPSHOTTYPE_PARTYSKILL_SPHERECIRCLE
	, SNAPSHOTTYPE_PARTYCHANGEITEMMODE
	, SNAPSHOTTYPE_PARTYCHANGEEXPMODE
	, SNAPSHOTTYPE_SET_PARTY_MEMBER_PARAM
	, SNAPSHOTTYPE_DO_ESCAPE
	, SNAPSHOTTYPE_SNOOP
	, SNAPSHOTTYPE_REMOVEITEMATID
	, SNAPSHOTTYPE_QUERYEQUIP
	, SNAPSHOTTYPE_RETURNSCORLL
	, SNAPSHOTTYPE_SETTARGET
	, SNAPSHOTTYPE_FOCUSOBJ
	, SNAPSHOTTYPE_SETQUEST
	, SNAPSHOTTYPE_FLYFF_EVENT
	, SNAPSHOTTYPE_SET_LOCAL_EVENT
	, SNAPSHOTTYPE_SETCHEERPARAM
	, SNAPSHOTTYPE_SETGUILDQUEST
	, SNAPSHOTTYPE_REMOVEGUILDQUEST
	, SNAPSHOTTYPE_ALLACTION
	, SNAPSHOTTYPE_GUILDCOMBAT
	, SNAPSHOTTYPE_DEFINEDCAPTION
	, SNAPSHOTTYPE_QUEST_TEXT_TIME
	, SNAPSHOTTYPE_QUERYPLAYERLISTSTRING
	, SNAPSHOTTYPE_CHATTEXT
	, SNAPSHOTTYPE_EXPBOXINFO
	, SNAPSHOTTYPE_EXPBOXCOLLTIME
	, SNAPSHOTTYPE_EXPBOXCOLLTIMECANCEL
	, SNAPSHOTTYPE_PLAYERPOS
	, SNAPSHOTTYPE_DESTPOS
	, SNAPSHOTTYPE_MOVERSETDESTOBJ
	, SNAPSHOTTYPE_DEFINEDTEXT1
	, SNAPSHOTTYPE_DEFINEDTEXT
	, SNAPSHOTTYPE_GAMETIMER
	, SNAPSHOTTYPE_TASKBAR
	, SNAPSHOTTYPE_MOTION
	, SNAPSHOTTYPE_QUERYPLAYERSTRING
	, SNAPSHOTTYPE_GUILD_INVITE
	, SNAPSHOTTYPE_SET_GUILD
	, SNAPSHOTTYPE_CREATE_GUILD
	, SNAPSHOTTYPE_DESTROY_GUILD
	, SNAPSHOTTYPE_GUILD
	, SNAPSHOTTYPE_ALL_GUILDS
	, SNAPSHOTTYPE_TEXT
	, SNAPSHOTTYPE_REVIVAL_BY_SKILL_MESSAGE
	, SNAPSHOTTYPE_REVIVAL_BY_SKILL
	, SNAPSHOTTYPE_REVIVAL_TO_CURRENT_POS
	, SNAPSHOTTYPE_REVIVAL_TO_LODESTAR
	, SNAPSHOTTYPE_REVIVAL_TO_LODELIGHT
	, SNAPSHOTTYPE_SET_STAT_LEVEL
	, SNAPSHOTTYPE_SET_JOB_LEVEL
	, SNAPSHOTTYPE_SET_GROWTH_LEARNING_POINT
	, SNAPSHOTTYPE_SET_JOB_SKILL
	, SNAPSHOTTYPE_SET_NEAR_JOB_SKILL
	, SNAPSHOTTYPE_RETURNSAY
	, SNAPSHOTTYPE_CREATESFXALLOW
	, SNAPSHOTTYPE_MOVINGACTMSG
	, SNAPSHOTTYPE_SETACTIONPOINT
	, SNAPSHOTTYPE_SETNAVIPOINT
	, SNAPSHOTTYPE_MOVERDEATH
	, SNAPSHOTTYPE_MOVERBEHAVIOR
	, SNAPSHOTTYPE_SETMOVEPATTERN
	, SNAPSHOTTYPE_SHOUT
	, SNAPSHOTTYPE_PLAYMUSIC
	, SNAPSHOTTYPE_PLAYSOUND
	, SNAPSHOTTYPE_MODIFYMODE
	, SNAPSHOTTYPE_DOAPPLYUSESKILL
	, SNAPSHOTTYPE_COMMONSKILL
	, SNAPSHOTTYPE_STATEMODE
	, SNAPSHOTTYPE_MELEE_ATTACK
	, SNAPSHOTTYPE_MAGIC_ATTACK
	, SNAPSHOTTYPE_RANGE_ATTACK
	, SNAPSHOTTYPE_SP_ATTACK
	, SNAPSHOTTYPE_ADDREGION
	, SNAPSHOTTYPE_GUILD_BANK_WND
	, SNAPSHOTTYPE_PUTITEMGUILDBANK
	, SNAPSHOTTYPE_GETITEMGUILDBANK
	, SNAPSHOTTYPE_GUILD_LOGO
	, SNAPSHOTTYPE_GUILD_CONTRIBUTION
	, SNAPSHOTTYPE_GUILD_NOTICE
	, SNAPSHOTTYPE_GUILD_AUTHORITY
	, SNAPSHOTTYPE_GUILD_PENYA
	, SNAPSHOTTYPE_GUILD_REAL_PENYA
	, SNAPSHOTTYPE_GUILD_CHANGEJOBLEVEL
	, SNAPSHOTTYPE_GUILD_ADDVOTE
	, SNAPSHOTTYPE_GUILD_MODIFYVOTE
	, SNAPSHOTTYPE_WAR
	, SNAPSHOTTYPE_REQUEST_GUILDRANK
	, SNAPSHOTTYPE_SEX_CHANGE
	, SNAPSHOTTYPE_WORLDMSG
	, SNAPSHOTTYPE_CALLTHEROLL
	, SNAPSHOTTYPE_ANGEL
	, SNAPSHOTTYPE_MINIGAME
	, SNAPSHOTTYPE_ULTIMATE
	, SNAPSHOTTYPE_EXCHANGE
	, SNAPSHOTTYPE_PET_CALL
	, SNAPSHOTTYPE_PET_RELEASE
	, SNAPSHOTTYPE_PET_LEVELUP
	, SNAPSHOTTYPE_PET_SET_EXP
	, SNAPSHOTTYPE_PET
	, SNAPSHOTTYPE_PET_STATE
	, SNAPSHOTTYPE_PET_FEED
	, SNAPSHOTTYPE_PET_MILL
	, SNAPSHOTTYPE_SET_SPEED_FACTOR
	, SNAPSHOTTYPE_MELEE_ATTACK2
	, SNAPSHOTTYPE_ENDSKILLQUEUE
	, SNAPSHOTTYPE_REMOVEMAIL
	, SNAPSHOTTYPE_QUERYMAILBOX
	, SNAPSHOTTYPE_CRIME
	, SNAPSHOTTYPE_SHIP_ACTMSG
	, SNAPSHOTTYPE_SUMMON
	, SNAPSHOTTYPE_MOTION_ARRIVE
	, SNAPSHOTTYPE_ADD_OBJ
	, SNAPSHOTTYPE_DEL_OBJ
	, SNAPSHOTTYPE_REPLACE
	, SNAPSHOTTYPE_REMOVE_GUILD_BANK_ITEM
	, SNAPSHOTTYPE_REMOVEALLSKILLINFULENCE
	, SNAPSHOTTYPE_DISGUISE
	, SNAPSHOTTYPE_NODISGUISE
	, SNAPSHOTTYPE_TAG
	, SNAPSHOTTYPE_REMOVESKILLINFULENCE
	, SNAPSHOTTYPE_LEGENDSKILLUP_RESULT
	, SNAPSHOTTYPE_EVENTLUA_DESC
	, SNAPSHOTTYPE_REMOVE_ATTRIBUTE
	, SNAPSHOTTYPE_START_COLLECTING
	, SNAPSHOTTYPE_STOP_COLLECTING
	, SNAPSHOTTYPE_GC1TO1_NOWSTATE
	, SNAPSHOTTYPE_GC1TO1_TENDEROPENWND
	, SNAPSHOTTYPE_GC1TO1_TENDERVIEW
	, SNAPSHOTTYPE_GC1TO1_MEMBERLINEUPOPENWND
	, SNAPSHOTTYPE_GC1TO1_WARRESULT
	, SNAPSHOTTYPE_UPDATE_ITEM_EX
	, SNAPSHOTTYPE_QUERY_PLAYER_DATA
	, SNAPSHOTTYPE_GUILDLOG_VIEW
	, SNAPSHOTTYPE_RESTART_COLLECTING
	, SNAPSHOTTYPE_SEALCHAR_REQ
	, SNAPSHOTTYPE_SEALCHARGET_REQ
	, SNAPSHOTTYPE_EVENT_COUPON
	, SNAPSHOTTYPE_POCKET_ATTRIBUTE
	, SNAPSHOTTYPE_POCKET_ADD_ITEM
	, SNAPSHOTTYPE_POCKET_REMOVE_ITEM
	, SNAPSHOTTYPE_QUE_PETRESURRECTION_RESULT
	, SNAPSHOTTYPE_REMOVESFXOBJ
	, SNAPSHOTTYPE_SECRETROOM_MNG_STATE
	, SNAPSHOTTYPE_SECRETROOM_INFO
	, SNAPSHOTTYPE_SECRETROOM_TENDEROPENWND
	, SNAPSHOTTYPE_SECRETROOM_LINEUPOPENWND
	, SNAPSHOTTYPE_SECRETROOM_TENDERVIEW
	, SNAPSHOTTYPE_HONOR_LIST_ACK
	, SNAPSHOTTYPE_HONOR_CHANGE_ACK
	, SNAPSHOTTYPE_QUESTHELPER_NPCPOS
	, SNAPSHOTTYPE_CLEAR_TARGET
	, SNAPSHOTTYPE_COUPLE
	, SNAPSHOTTYPE_PROPOSE_RESULT
	, SNAPSHOTTYPE_COUPLE_RESULT
	, SNAPSHOTTYPE_DECOUPLE_RESULT
	, SNAPSHOTTYPE_ADD_COUPLE_EXPERIENCE
	, SNAPSHOTTYPE_RESETDESTPARAM_SYNC
	, SNAPSHOTTYPE_PCBANG_INFO
	, SNAPSHOTTYPE_ACCOUNT_PLAYTIME
	, SNAPSHOTTYPE_SMELT_SAFETY
	, SNAPSHOTTYPE_WORLD_READINFO
	, SNAPSHOTTYPE_QUIZ_STATE
	, SNAPSHOTTYPE_QUIZ_MESSAGE
	, SNAPSHOTTYPE_QUIZ_QUESTION
	, SNAPSHOTTYPE_MOVER_CHANGESFX
	, SNAPSHOTTYPE_VISPET_ACTIVATE
	, SNAPSHOTTYPE_GUILDHOUSE_PACKET
	, SNAPSHOTTYPE_GUILDHOUSE_ALLINFO
	, SNAPSHOTTYPE_GUILDHOUSE_REMOVE
	, SNAPSHOTTYPE_GUILDHOUSE_RESTPOINT
	, SNAPSHOTTYPE_QUEST_CHECKED
	, SNAPSHOTTYPE_CAMPUS_INVITE
	, SNAPSHOTTYPE_CAMPUS_UPDATE
	, SNAPSHOTTYPE_CAMPUS_REMOVE
	, SNAPSHOTTYPE_CAMPUS_UPDATE_POINT
	, SNAPSHOTTYPE_ITEM_SELECT_AWAKENING_VALUE		// 사용 안함
	, SNAPSHOTTYPE_GUILDHOUSE_TENDER_MAINWND
	, SNAPSHOTTYPE_GUILDHOUSE_TENDER_INFOWND
	, SNAPSHOTTYPE_GUILDHOUSE_TENDER_RESULT
	, SNAPSHOTTYPE_QUERYMAILBOX_REQ
	, SNAPSHOTTYPE_ITEM_LINK_INFO
	, SNAPSHOTTYPE_SETSLEEPING
	, SNAPSHOTTYPE_CALL_BARUNA_NPC
	, SNAPSHOTTYPE_BARUNA_NPC_INFO
	, SNAPSHOTTYPE_RELEASE_BARUNA_NPC
	, SNAPSHOTTYPE_TAX_ALLINFO
	, SNAPSHOTTYPE_TAX_SETTAXRATE_OPENWND
	, SNAPSHOTTYPE_ELECTION_ADD_DEPOSIT
	, SNAPSHOTTYPE_ELECTION_SET_PLEDGE
	, SNAPSHOTTYPE_ELECTION_INC_VOTE
	, SNAPSHOTTYPE_ELECTION_BEGIN_CANDIDACY
	, SNAPSHOTTYPE_ELECTION_BEGIN_VOTE
	, SNAPSHOTTYPE_ELECTION_END_VOTE
	, SNAPSHOTTYPE_LORD
	, SNAPSHOTTYPE_L_EVENT
	, SNAPSHOTTYPE_L_EVENT_CREATE
	, SNAPSHOTTYPE_L_EVENT_INITIALIZE
	, SNAPSHOTTYPE_LORD_SKILL_TICK
	, SNAPSHOTTYPE_L_EVENT_TICK
	, SNAPSHOTTYPE_SET_TUTORIAL_STATE
	, SNAPSHOTTYPE_LORD_SKILL_USE
	, SNAPSHOTTYPE_RAINBOWRACE_PREVRANKING_OPENWND
	, SNAPSHOTTYPE_RAINBOWRACE_APPLICATION_OPENWND
	, SNAPSHOTTYPE_RAINBOWRACE_NOWSTATE
	, SNAPSHOTTYPE_RAINBOWRACE_MINIGAMESTATE
	, SNAPSHOTTYPE_RAINBOWRACE_MINIGAMEEXTSTATE
	, SNAPSHOTTYPE_SET_PET_NAME
	, SNAPSHOTTYPE_HOUSING_ALLINFO
	, SNAPSHOTTYPE_HOUSING_FURNITURELIST
	, SNAPSHOTTYPE_HOUSING_SETUPFURNITURE
	, SNAPSHOTTYPE_HOUSING_PAPERINGINFO
	, SNAPSHOTTYPE_HOUSING_SETVISITALLOW
	, SNAPSHOTTYPE_HOUSING_VISITABLELIST
	, SNAPSHOTTYPE_BARUNA16_OPER_EXTRACT
	, SNAPSHOTTYPE_BARUNA16_OPER_CREATE
	, SNAPSHOTTYPE_BARUNA16_CID_CREATE
	, SNAPSHOTTYPE_BARUNA16_CIDPIECE_UPGRADE
	, SNAPSHOTTYPE_BARUNA16_OPERCID_CREATE
	, SNAPSHOTTYPE_GUILDHOUSE_INFOWND
	, SNAPSHOTTYPE_RESET_BIND
	, SNAPSHOTTYPE_BUY_SHOPPING_BASKET

	/////////////////////// 협동 기부 ///////////////////////////
	//, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_INFO_REQ
	, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_INFO_ACK
	, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_ACK
	//, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_REQ
	//, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_ITEM_ACK
	//, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_GOLD_ACK
	, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_CONTRIBUTE_GET_RANKING_ACK

	, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_REWARD_BUFF

	//, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_GLOBAL_REWARD_INFO_FLOAT
	//, SNAPSHOTTYPE_COOPERATIVE_CONTRIBUTIONS_GLOBAL_REWARD_INFO_INT
	/////////////////////// 협동 기부 ///////////////////////////


	//콜로세움
	, SNAPSHOTTYPE_COLOSSEUM_ENTER_ACK					//SC 콜로세움 입장 응답
	, SNAPSHOTTYPE_COLOSSEUM_RETRY_ACK					//SC 재시도 응답

	, SNAPSHOTTYPE_COLOSSEUM_AUTO_INVITE_REQ			//SC 자동 초대

	, SNAPSHOTTYPE_COLOSSEUM_AUTO_START_WAITING_TICK	//SC 자동 시작 대기 시간
	, SNAPSHOTTYPE_COLOSSEUM_STAGE_WAITING_TICK			//SC 스테이지 준비 대기 시간

	, SNAPSHOTTYPE_COLOSSEUM_STARTED_STAGE				//SC 스테이지 시작됨 & 몬스터 제한시간
	, SNAPSHOTTYPE_COLOSSEUM_CLEARED_STAGE				//SC 스테이지 완료됨
	, SNAPSHOTTYPE_COLOSSEUM_STAGE_TIME_LIMIT			//SC 스테이지 시간 만료 & 재시도 대기 시간
	, SNAPSHOTTYPE_COLOSSEUM_ALL_DIE					//SC 파티원 모두 사망 & 재시도 대기 시간

	, SNAPSHOTTYPE_COLOSSEUM_RETRIED					//SC 재시도 됨 & 재시도 스테이지 시작 시간
	, SNAPSHOTTYPE_COLOSSEUM_ALL_CLEAR					//SC 모든 스테이지 클리어 & 완료 대기시간 & 보상 정보


	, SNAPSHOTTYPE_COLOSSEUM_REGIST_ADDITIONAL_REAL_MONSTER_RATE_ITEM_ACK		//SC 리얼 몬스터 출연 확률 올려주는 아이템 등록
	, SNAPSHOTTYPE_COLOSSEUM_UNREGIST_ADDITIONAL_REAL_MONSTER_RATE_ITEM_ACK		//SC 리얼 몬스터 출연 확률 올려주는 아이템 등록해제
	, SNAPSHOTTYPE_COLOSSEUM_REGISTED_ADDITIONAL_REAL_MONSTER_RATE_ITEM_NOTI		//SC 리얼 몬스터 출연 확률 올려주는 아이템 등록

	, SNAPSHOTTYPE_COLOSSEUM_RANKING_INFO					// 랭킹


	//, SNAPSHOTTYPE_COLOSSEUM_KICK						//SC 인던에서 ?겨남

	//, SNAPSHOTTYPE_COLOSSEUM_REWARD_GOLD_INFO			//콜로세움 보상 골드 보상 정보
	//, SNAPSHOTTYPE_COLOSSEUM_REWARD_ITEM_LIST_INFO		//콜로세움 보상 아이템 리스트 정보
	//-콜로세움

	, SNAPSHOTTYPE_TELEPORT_MAP_OPEN_NOTI				// 텔레포트 지도 오픈
	, SNAPSHOTTYPE_TELEPORT_MAP_TO_POINT_ACK			// 텔레포트 요청 응답
	, SNAPSHOTTYPE_TELEPORT_MAP_ADD_MY_POINT_ACK		// 텔레포트 지도 아이템 현재 위치 등록 응답
	, SNAPSHOTTYPE_TELEPORT_MAP_CHG_POINT_NAME_ACK		// 텔레포트 지도 아이템 등록 위치 이름 수정 응답
	, SNAPSHOTTYPE_TELEPORT_MAP_DEL_POINT_ACK			// 텔레포트 지도 아이템 등록 위치 삭제 응답
	, SNAPSHOTTYPE_TELEPORT_MAP_DEL_ALL_POINT_ACK		// 텔레포트 지도 아이템 등록 위치 모두 삭제 응답

	
	// 이벤트용 아레나(참가 선수)
	, SNAPSHOTTYPE_EVENT_ARENA_TEAM_INFO_NOTI			// 팀 정보 통보
	, SNAPSHOTTYPE_EVENT_ARENA_TEAM_MEMBER_UPDATE_NOTI	// 팀원 정보 갱신(변경된 팀원만)
	, SNAPSHOTTYPE_EVENT_ARENA_CALL_PLAYER_NOTI			// 선수소환 대기 통보


	// 이벤트용 아레나(공용)
	, SNAPSHOTTYPE_EVENT_ARENA_GAME_JOIN_TEAM_INFO_NOTI	// 게임에 참여하는 레드, 블루팀 정보
	, SNAPSHOTTYPE_EVENT_ARENA_BATTLE_RESULT_NOTI		// 전투 결과 통보
	, SNAPSHOTTYPE_EVENT_ARENA_GAME_RESULT_NOTI			// 게임 결과(최종 승리) 통보
	, SNAPSHOTTYPE_EVENT_ARENA_GAME_SCOREBOARD_NOTI		// 게임 전광판 통보
	, SNAPSHOTTYPE_EVENT_ARENA_BATTLE_RESULT_LOG_NOTI	// 전투 결과 로그 통보


	// 이벤트용 아레나(관리자)
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_WINDOW_OPEN_NOTI				// 관리창 오픈 통보
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_WINDOW_CLOSE_NOTI				// 관리창 닫기 통보
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_GAME_INFO_SYNC_NOTI			// 게임 정보 동기 요청
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_WAIT_CALL_PLAYERS_NOTI		// 선수소환 대기 통보
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_RED_BLUE_TEAM_INFO_NOTI		// 레드, 블루 팀 정보 통보(주기적으로 전송)
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_RED_BLUE_TEAM_INFO_CLOSE_NOTI	// 레드, 블루 팀 정보 창 닫기 통보
	, SNAPSHOTTYPE_EVENT_ARENA_MANAGE_WAIT_JOIN_PLAYERS_NOTI		// 선수입장 대기 통보

	////X TRAP
	//, SNAPSHOTTYPE_XTRAP_COMMAND_REQUEST

	, SNAPSHOTTYPE_ITEM_UPGRADE_RANDOM_OPTION_ACK							// 각성 옵션 정보

	// 아이템 업그레이드
	, SNAPSHOTTYPE_ITEM_UPGRADE_GENERAL_ENCHANT_RESULT_ACK					// 일반 제련 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_ATTRIBUTE_ENCHANT_RESULT_ACK				// 속성 제련 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_ATTRIBUTE_CHANGE_RESULT_ACK					// 속성 변경 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_ATTRIBUTE_REMOVE_RESULT_ACK					// 속성 제거 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_PIERCING_SIZE_INCREASE_RESULT_ACK			// 피어싱 소켓 사이즈 증가 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_PIERCING_ITEM_INSERT_RESULT_ACK				// 피어싱 아이템 넣기 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_PIERCING_ITEM_REMOVE_RESULT_ACK				// 피어싱 아이템 빼기 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_RANDOM_OPTION_GENERATE_RESULT_ACK			// 각성 옵션 부여 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_RANDOM_OPTION_INITIALIZE_RESULT_ACK			// 각성 옵션 제거 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_EQUIP_LEVEL_DECREASE_RESULT_ACK				// 착용 레벨 하락 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_EQUIP_LEVEL_INITIALIZE_RESULT_ACK			// 착용 레벨 하락 제거 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_COMBINE_RESULT_ACK							// 아이템 합성 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_COMBINE_INITIALIZE_DATA_ACK					// 아이템 합성 취소 데이터 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_COMBINE_INITIALIZE_RESULT_ACK				// 아이템 합성 취소 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_LOOKS_CHANGE_RESULT_ACK						// 아이템 외형 변경 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_LOOKS_INITIALIZE_RESULT_ACK					// 아이템 외형 변경 취소 결과 통보
	, SNAPSHOTTYPE_ITEM_UPGRADE_COMBINED_OPTION_ACK							// 합성 옵션 정보

	, SNAPSHOTTYPE_FF_SET_POSTION_INFO


	, SNAPSHOTTYPE_ITEM_MERGE_RESULT_ACK		// 아이템 합성 결과 통보


	, SNAPSHOTTYPE_CHARGE_ZONE_TICKET_ENTERANCE_NOTI			// 유료 지역 입장 오픈
	, SNAPSHOTTYPE_CHARGE_ZONE_TICKET_LEAVE_NOTI				// 유료 지역 퇴장 오픈

	, SNAPSHOTTYPE_TREASURE_CHEST_OPEN_NOTI						// 보물 상자 UI 오픈
	, SNAPSHOTTYPE_TREASURE_CHEST_OPEN_BY_KEY_ACK				// 보물 상자 오픈

	// 거래 중개 
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_USER_INFO_ACK					// 유저 개인 정보
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_REGIST_ACK						// 등록
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_CANCEL_REGISTED_ACK				// 등록 취소
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_REGISTED_INFO_LIST_ACK				// 등록 리스트 
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_BUY_ITEM_ACK					// 구매
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_SELL_ITEM_NOTI					// 실시간 판매 정보 ( 판매자용 )
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_COLLECT_GOLD_ACK				// 정산 판매 골드
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_SEARCH_ACK						// 검색
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_SALE_GOLD_INFO_LIST_ACK			// 정산 판매 골드 정보
	, SNAPSHOTTYPE_CONSIGNMENT_SALE_CALC_TAX_ACK					// 세금 계산해서 얻기


	, SNAPSHOTTYPE_CHARACTER_SERVER_TRANSFORM_OPEN_NOTI				// 캐릭터 서버군 이동 UI오픈


	, SNAPSHOTTYPE_SET_AUTHORIZATION_NOTI							// 캐릭터 권한 설정

	//, SNAPSHOTTYPE_JOIN												// 로그인 관련
	, SNAPSHOTTYPE_USE_ACTION_SLOT_NOTI								// 액션 슬롯 사용 가능 통보

	, SNAPSHOTTYPE_ITEM_UPGRADE_RANDOM_OPTION_GENERATE_RETRY_RESULT_ACK	// 각성 옵션 부여 재시도 결과 통보

	, SNAPSHOTTYPE_ITEM_UPGRADE_RANDOM_OPTION_SYNC_ACK				// 각성 옵션 싱크 응답
	, SNAPSHOTTYPE_CHANGE_PARTY_KIND_NOTI							// 극단 종류 변경

	, SNAPSHOTTYPE_SET_PARTY_EFFECT_MODE_NOTI

	, SNAPSHOTTYPE_MADRIGAL_GIFT_POINT_NOTI

	, SNAPSHOTTYPE_REFRESH_PARTY_EFFECT_MODE_NOTI

	, SNAPSHOTTYPE_MADRIGAL_GIFT_ITEM_RECV_ACK

	, SNAPSHOTTYPE_FLYFF_PIECE_EXCHANGE_LIST_ACK
	, SNAPSHOTTYPE_EXCHANGE_FLYFF_PIECE_ITEM_ACK

	, SNAPSHOTTYPE_MADRIGAL_GIFT_SYSTEM_ACTIVATION_NOTI

	, SNAPSHOTTYPE_SELL_ITEM_TO_NPC_ACK

	, SNAPSHOTTYPE_ACTION_SLOT_SKILL_SKIP

	, SNAPSHOTTYPE_REFRESH_BUFF_ADJVALUE

	, SNAPSHOTTYPE_ITEM_EXCHANGE_ACK

	, SNAPSHOTTYPE_ITEM_USING_ACK

	, SNAPSHOTTYPE_SEASON_INFO
	, SNAPSHOTTYPE_SEASON_EFFECT
#ifdef INVENTORY_ITEM_ALIGN
	, SNAPSHOTTYPE_ALIGNITEM
#endif	// INVENTORY_ITEM_ALIGN
#ifdef PAT_LOOTOPTION
	, SNAPSHOTTYPE_PETLOOTOPTION
#endif // PAT_LOOTOPTION
#ifdef BARUNA_ULTIMATE_UPDATE
	, SNAPSHOTTYPE_ITEM_UPGRADE_ULTIMATE_TRANS_RESULT_ACK
#endif
#ifdef CARD_UPGRADE_SYSTEM
	, SNAPSHOTTYPE_ITEM_UPGRADE_CARD_RESULT_ACK
#endif	// CARD_UPGRADE_SYSTEM
#ifdef COSTUME_UPGRADE_ENHANCEMENT_GEM
	, SNAPSHOTTYPE_ITEM_UPGRADE_SETGEM_RESULT_ACK
	, SNAPSHOTTYPE_ITEM_UPGRADE_REMOVEGEM_RESULT_ACK
#endif
#ifdef __DROP_LOG
    , SNAPSHOTTYPE_REAP_GOLD
#endif // __DROP_LOG
#ifdef COSTUME_UPGRADE_MIX
	, SNAPSHOTTYPE_ITEM_UPGRADE_MIX_RESULT_ACK
#endif
#ifdef __ZCK_SFX_AMELIORER
	, SNAPSHOTTYPE_ZCK_SFX_EQUIPINFO
#endif // __ZCK_SFX_AMELIORER
#ifdef __ZCK_WORLD_BOSS
	, SNAPSHOTTYPE_WORLDBOSS_INFO
#endif // __ZCK_WORLD_BOSS
#ifdef __ZCK_INVASIONS
	, SNAPSHOTTYPE_ZCK_INVASIONS
#endif // __ZCK_INVASIONS
#ifdef __ZCK_RECORD
	, SNAPSHOTTYPE_ZCK_RECORD
#endif // __ZCK_RECORD

#ifdef __COOLDOWN_TIMER
, SNAPSHOTTYPE_NEXTGUILDWAR
, SNAPSHOTTYPE_NEXTPLAYERSIEGE
, SNAPSHOTTYPE_TIMER
, SNAPSHOTTYPE_DUNGEONCOOLTIME
#endif

#ifdef __INFO_DUNGEONS //
, SNAPSHOTTYPE_DUNGEON_INFOLIST
, SNAPSHOTTYPE_UPDATE_INFOPLAYER
#endif

#ifdef __POSI_BUG_FIX
, SNAPSHOTTYPE_POSBUG_INFO
, SNAPSHOTTYPE_FF_SET_POSITION_INFO
#endif
};

// END SNAPSHOTTYPE
//////////////////////////////////////////////////////////////////////////


enum	FLMONITOR_PACKET
{
	PACKETTYPE_DEBUG_EXTERN_DUMP_OPTION_NOTI	= PACKETTYPE_TERMINATE_PROCESS+100,	// 프로세스 닫을때 외부 덤프 옵션
	PACKETTYPE_DEBUG_DUMP_PROCESS_NOTI,												// 현재 프로세스의 덤프를 남김
};



////////////////////////////////////////////////////////////////////////////
//  ERROR define
////////////////////////////////////////////////////////////////////////////
#define ERROR_OK							0L
#define ERROR_DEFAULT						1L

#define	ERROR_ACCOUNT_EXISTS				100L
#define ERROR_INVALID_SERVICE_PLAYER		102L
#define ERROR_DUPLICATE_ACCOUNT				103L
#define ERROR_ILLEGAL_ACCESS				104L
#define ERROR_DUPLICATE_SLOT				105L
#define ERROR_SLOT_OUTOFRANGE				106L
#define	ERROR_ILLEGAL_VER					107L
#define	ERROR_OVERFLOW						108L
#define	ERROR_EXTERNAL_ADDR					109L
#define	ERROR_INVALID_CLOCK					110L
#define ERROR_INVALID_NAME_CHARACTER		111L
#define	ERROR_WARTIME						112L
#define ERROR_BLOCKGOLD_ACCOUNT				119L
#define ERROR_FLYFF_PASSWORD				120L	// 비밀 번호가 틀립니다.
#define ERROR_FLYFF_ACCOUNT					121L	// 잘못된 계정입니다.
#define ERROR_FLYFF_AUTH					122L	// 실명인증후 게임접속이 가능합니다
#define ERROR_FLYFF_PERMIT					123L    // 프리프는 12세 이상 이용가 이므로 게임접속을 할수 없습니다.
#define ERROR_FLYFF_NEED_AGREEMENT			124L	// 14세 미만 가입자 분들은 부모님 동의서를 보내주셔야
#define ERROR_FLYFF_NO_MEMBERSHIP			125L	// 웹에서 탈퇴한 계정입니다
#define ERROR_BILLING_INFO_FAILED			126L	// 빌링 정보 없음
#define ERROR_BILLING_DATABASE_ERROR		127L	// 빌링 DB 에러 
#define ERROR_BILLING_TIME_OVER				128L	// 빌링 사용시간 만료 
#define ERROR_BILLING_OTHER_ERROR			129L	// 빌링 기타 다른 에러 
#define ERROR_BILLING_DISCONNECTED			130L	// 서버 접속 해제
#define ERROR_TOO_LATE_PLAY					131L	// 태국 22시에서 06시까지만 플레이 가능합니다.
#define ERROR_IP_CUT						132L	// 해외에서 국내로 못들어옴
#define ERROR_FLYFF_DB_JOB_ING				133L	// 실시간 데이터 작업 유저		
#define ERROR_15SEC_PREVENT					134L	// 15초간 로그인 금지 
#define ERROR_15MIN_PREVENT					135L	// 15분간 로그인 금지 
#define ERROR_CERT_GENERAL					136L	// CERT 일반 오류 	
#define	ERROR_FLYFF_EXPIRED_SESSION_PASSWORD	137L	// 세션 패스워드 만료
#define	ERROR_USER_OVERFLOW					138L	// 캐릭터 생성 수 초과
#define	ERROR_SLOT_DONOT_CREATE				139L	// 해당 서버에서는 캐릭터를 생성할 수 없습니다.
#define	ERROR_SLOT_DONOT_DELETE				140L	// 해당 서버에서는 캐릭터를 삭제할 수 없습니다.
#define ERROR_SHUTDOWN_RULE					141L	// SHUTDOWN제도에 걸립니다.

#define ERROR_JAPAN_AUTH_BASEVALUE			150L
#define	ERROR_JAPAN_AUTH_CONVERTED_USER		150L	// 일본 인증 결과 :변환한 flyff 유저 
#define	ERROR_JAPAN_AUTH_NEED_AGREEMENT		151L	// 일본 인증 결과 :Web 페이지 호출
#define	ERROR_JAPAN_AUTH_ID_ERROR			152L	// 일본 인증 결과 :DATA NOT FOUND
#define	ERROR_JAPAN_AUTH_PASSWORD_ERROR		153L	// 일본 인증 결과 :패스워드 맞지 않음
#define	ERROR_JAPAN_AUTH_BLOCK				154L	// 일본 인증 결과 :block user
#define	ERROR_JAPAN_AUTH_AGREE				155L	// 일본 인증 결과 :ok
#define	ERROR_JAPAN_AUTH_PARAMETER_ERROR	156L	// 일본 인증 결과 :Parameter Error
#define	ERROR_JAPAN_AUTH_REJECT				157L	// 일본 인증 결과 :로그인 실패 횟수 초과로 인한 로그인 금지 상태
#define	ERROR_JAPAN_AUTH_HANGAME_ERROR		158L	// 일본 인증 결과 :한게임으로부터의 리턴값이 없음
#define	ERROR_JAPAN_AUTH_FAIL				159L	// 일본 인증 결과 :시스템 에러

#define	ERROR_INDONESIA_AUTH_DUPLICATED_LOGIN	160L	// 인도네시아 인증 결과: 다른 게임에 로그인 되어 있습니다. 5분후 다시 접속요망
#define	ERROR_INDONESIA_AUTH_ID_PASSWORD_WRONG	161L	// 인도네시아 인증 결과: ID 혹은 Password가 잘못되었습니다.

#define ERROR_WEBZEN_ACCOUNT_ID_CONVERTING_FAIL	162L
#define ERROR_WEBZEN_TERMS_AGREEMENT			163L
#define ERROR_WEBZEN_TRY_CONNECT_BLOCKING_AREA	164L
#define ERROR_WEBZEN_GDPR_AGREEMENT				165L

// Party
#define ERROR_NOLEADER						200L
#define ERROR_FULLPARTY						201L
#define ERROR_NOPARTY						202L
#define ERROR_DIFFRENTPARTY					203L
#define ERROR_DIFFERNTUSERNAME				204L
#define ERROR_NOTPARTYPOINT					205L
#define ERROR_NOTPARTYSKILL					206L
#define ERROR_NOTTARGET						207L
#define ERROR_NOTMAMBER						208L
#define ERROR_SAMLEADER						209L
#define ERROR_INVITE_SUCCESS				210L

// NOERR_XXX 와 ERROR_XXX 는 중복되면 안된다.
#define	NOERR_REGISTER_ACCOUNT				500L		
#define NOERR_LOGIN							501L


#define	ERROR_NODE_NOT_FOUND				1000L


#define WEBZEN_ACCOUNT_ID_CONVERTING_FAIL	100
#define WEBZEN_GDPR_AGREEMENT				90145
#define WEBZEN_TERMS_AGREEMENT				90206
#define	WEBZEN_TRY_CONNECT_BLOCKING_AREA	90220

////////////////////////////////////////////////////////////////////////////
//  QPS_ define
////////////////////////////////////////////////////////////////////////////
#define	QPS_GUILD_MASTER	(BYTE)0x00
#define	QPS_GUILD_MEMBER	(BYTE)0x01
#define	QPS_POST	(BYTE)0x02
#define	QPS_GENERIC	(BYTE)0x03
#define	QPS_GUILDCOMBAT_RANKING	(BYTE)0x04


typedef	struct	_runscriptfunc
{
	char	lpszVal1[1024];
	char	lpszVal2[1024];
	DWORD	dwVal1;
	DWORD   dwVal2;
	WORD	wFuncType;
#if !defined (__CLIENT) && !defined(__WORLDSERVER) && !defined(__DBSERVER)
	vector3 vPos;
#else
	D3DXVECTOR3 vPos;
#endif
}	RunScriptFunc, *PRunScriptFunc;

#define	FUNCTYPE_ADDKEY			(WORD)0x0010
#define	FUNCTYPE_REMOVEKEY		(WORD)0x0011
#define	FUNCTYPE_SAY			(WORD)0x0012
#define	FUNCTYPE_ADDANSWER		(WORD)0x0013
#define	FUNCTYPE_SETMARK		(WORD)0x0014
#define	FUNCTYPE_GOMARK			(WORD)0x0015
#define	FUNCTYPE_EXIT			(WORD)0x0016
#define	FUNCTYPE_ENDSAY			(WORD)0x0017
#define	FUNCTYPE_CREATEGUILD	(WORD)0x0018
#define	FUNCTYPE_DESTROYGUILD	(WORD)0x0019
#define	FUNCTYPE_INITSTAT		(WORD)0x001a
#define	FUNCTYPE_SETNAVIGATOR	(WORD)0x001b
#define	FUNCTYPE_REMOVENAVIGATOR	(DWORD)0x001c
#define	FUNCTYPE_REMOVEALLKEY	(WORD)0x001d
#define	FUNCTYPE_SAYQUEST		(WORD)0x001e
#define	FUNCTYPE_INITSTR		(WORD)0x0020
#define	FUNCTYPE_INITSTA		(WORD)0x0021
#define	FUNCTYPE_INITDEX		(WORD)0x0022
#define	FUNCTYPE_INITINT		(WORD)0x0023
#define	FUNCTYPE_QUERYSETPLAYERNAME	(DWORD)0x0024
#define	FUNCTYPE_QUERYSETGUILDNAME	(DWORD)0x0025
#define	FUNCTYPE_NEWQUEST		(WORD)0x0026
#define	FUNCTYPE_CURRQUEST		(WORD)0x0027

// port num
#define	PN_PATCHSRVR	1100
#define	PN_WORLDSRVR	2000
#define	PN_CERTIFIER	23000
#define	PN_CORESRVR	4000
#define	PN_CACHESRVR	5400
#define	PN_DBSRVR_0		7000	// l
//#define	PN_DBSRVR_1		7100	// w
#define	PN_DBSRVR_1		24000	// w
#define PN_DBSRVR_2		7200	// core
#define	PN_LOGINSRVR	28000
#define	PN_PATCH_DISTRIBUTOR_0	9000
#define	PN_PATCH_DISTRIBUTOR_1	9100

#define	PN_MONITOR_0	11000		// 사용안함
#define	PN_MONITOR_1	11001		// 터미널
#define	PN_MONITOR_2	11002		// 런처

#define	PN_ACCOUNTSRVR_0	12000
#define	PN_ACCOUNTSRVR_1	12001
#define	PN_ACCOUNTSRVR_2	12002

#define	PN_ACCUMULATOR		13000

#define	PN_ADBILL		29000

#define PN_COLLECTION	26000


// PACKETTYPE_ADD_ACCOUNT의 리턴 코드
const BYTE ACCOUNT_DUPLIACTE     = 0;			// 중복 에러 
const BYTE ACCOUNT_CHECK_OK      = 1;			// 성공
const BYTE ACCOUNT_EXTERNAL_ADDR = 2;			// 허용되지 않는 주소 
const BYTE ACCOUNT_OVERFLOW      = 3;			// 인원초과
const BYTE ACCOUNT_BILLING_INFO_FAILED    = 4;	// 빌링 정보 없음 
const BYTE ACCOUNT_BILLING_DATABASE_ERROR = 5;	// 빌링 DB 에러 
const BYTE ACCOUNT_BILLING_TIME_OVER      = 6;	// 빌링 사용시간 만료 
const BYTE ACCOUNT_BILLING_OTHER_ERROR    = 7;	// 빌링 기타 다른 에러 
const BYTE ACCOUNT_BILLING_DISCONNECTED	  = 8;  // 빌링 서버가 끊겨 있는 경우
const BYTE ACCOUNT_IPCUT_ADDR	  = 9;  // 빌링 서버가 끊겨 있는 경우

const BYTE ACCOUNT_BILLING_WAIT_ACK	      = 128;  // 빌링응답을 기다리는 경우 

//
// m_cbAccountFlag의 의미 
//
const BYTE ACCOUNT_FLAG_18           = 0x01;		// 18세이상 
const BYTE ACCOUNT_FLAG_SCHOOLEVENT  = 0x02;		// 학교대항전 이벤트 참가가능자?
const BYTE ACCOUNT_FLAG_UNREGISTER18 = 0x04;		// 미등록 성인 
const BYTE ACCOUNT_FLAG_HANGAME		 = 0x08;		// 한게임 사용자





#define CHATTING_ENTERMEMBER		(BYTE)0x00
#define CHATTING_NEWCHATTING		(BYTE)0x01
#define CHATTING_DELETECHATTING		(BYTE)0x02
#define CHATTING_REMOVEMEMBER		(BYTE)0x03
#define CHATTING_CHATTING			(BYTE)0x04
#define CHATTING_CHATTINGROOMSTATE	(BYTE)0x05

#define GAME_RATE_SHOPCOST		(BYTE)0x00
#define GAME_RATE_ITEMDROP		(BYTE)0x01
#define GAME_RATE_GOLDDROP		(BYTE)0x02
#define GAME_RATE_MONSTEREXP	(BYTE)0x03
#define GAME_RATE_MONSTERHIT	(BYTE)0x04
#define GAME_RATE_X3			(BYTE)0x05	// GAME_RATE_ITEMDROP, //GAME_RATE_GOLDDROP, //GAME_RATE_MONSTEREXP
#define GAME_RATE_REBIRTH		(BYTE)0x06
#define GAME_RATE_HITPOINT		(BYTE)0x07
#define GAME_RATE_AGGRESSIVE	(BYTE)0x08
#define GAME_RATE_RESPAWN		(BYTE)0x09
#define GAME_SKILL_VAGSP		(BYTE)0x10
#define GAME_SKILL_EXPERTSP		(BYTE)0x11
#define GAME_SKILL_PROSP		(BYTE)0x12

#define GAME_RATE_SHOP_BUY		(BYTE)0x13
#define GAME_RATE_SHOP_SELL		(BYTE)0x14




const BYTE COMMONPLACE_ACTION	= 0x00;
const BYTE COMMONPLACE_ALPHA	= 0x01;
const BYTE COMMONPLACE_QUAKE	= 0x02;
//const BYTE COMMONPLACE_ERROR	= 0x03;


//현상금 처리관련 
const BYTE CT_WANTED_REQ_LIST   = 0x00;		// Core->Trans 리스트 요청 
const BYTE CT_WANTED_SET		= 0x01;		// Core->Trans 현상금 설정 

const BYTE GC_WINGUILD			= 0x00;		// 이긴 길드 정보
const BYTE GC_IN_WINDOW			= 0x01;		// 대전 신청 창 띄움
const BYTE GC_IN_APP			= 0x02;		// 대전 신청
const BYTE GC_IN_COMPLETE		= 0x03;		// 길드대전 신청 완료
const BYTE GC_REQUEST_STATUS	= 0x04;		// 대전 신청 현황
const BYTE GC_SELECTPLAYER		= 0x05;		// 길드대전 선택 캐릭터 창 띄움
const BYTE GC_SELECTWARPOS		= 0x06;		// 대전위치 윈도우 띄움
const BYTE GC_BESTPLAYER		= 0x07;		// BEST Player 정보
const BYTE GC_ISREQUEST			= 0x08;		// 신청중인지?
const BYTE GC_USERSTATE			= 0x10;		// 유저상태
const BYTE GC_WARPLAYERLIST		= 0x11;		// 전쟁유저 정보
const BYTE GC_GUILDSTATUS		= 0x20;		// 자신의 길드 상황
const BYTE GC_GUILDPRECEDENCE	= 0x21;		// 길드 순위
const BYTE GC_PLAYERPRECEDENCE	= 0x22;		// 개인 순위
const BYTE GC_GCSTATE			= 0x30;		// 대전 상황	
const BYTE GC_NEXTTIMESTATE		= 0x31;		// 대전시 다음 시간과 상태 넘겨주기
const BYTE GC_ENTERTIME			= 0x32;		// 대전시 들어갈수 있는 시간
const BYTE GC_DIAGMESSAGE		= 0x33;		// 다이얼 로그 메세지
const BYTE GC_TELE				= 0x34;		// 텔레포트
const BYTE GC_LOG				= 0x35;		// 대전 로그( 대전이 끝나면 나오게~ )
const BYTE GC_LOG_REALTIME		= 0x36;		// 대전 로그( 실시간으로 채팅창에 나오게~ )
const BYTE GC_GETPENYAGUILD		= 0x40;		// 길드 신청금액 및 보상
const BYTE GC_GETPENYAPLAYER	= 0x41;		// 베스트 플레이어 보상
const BYTE GC_PLAYERPOINT		= 0x42;		// 길드대전 플레이어 포인트

const BYTE SOMMON_FRIEND			= 0x00;		// 친구 소환
const BYTE SOMMON_FRIEND_CONFIRM	= 0x01;		// 친구 소환 확인
const BYTE SOMMON_PARTY_CONFIRM		= 0x10;		// 파티 소환

const BYTE LOG_SKILLPOINT_GET_QUEST		= 0x00;		// 스킬포인트 얻기 - 퀘스트
const BYTE LOG_SKILLPOINT_GET_HUNT		= 0x01;		// 스킬포인트 얻기 - 몬스터
const BYTE LOG_SKILLPOINT_GET_REWARD	= 0x02;		// 스킬포인트 얻기 - 스킬포인트 맥스 제한 풀리면서 보상
const BYTE LOG_SKILLPOINT_USE			= 0x10;		// 스킬포인트 쓰기 - 스킬레벨업

const BYTE PK_PINK					= 0x00;		// 핑크상태 전송
const BYTE PK_PROPENSITY			= 0x01;		// 카오성향 전송
const BYTE PK_PKVALUE				= 0x02;		// 카오수치 전송

//const BYTE ANGEL_WNDCREATE			= 0x00;		// 엔젤창
const BYTE ANGEL_INFO				= 0x01;		// 엔젤 정보 주기(경험치, 레벨)

const BYTE TEXT_GENERAL				= 0x01;		// OnText
const BYTE TEXT_DIAG				= 0x02;		// OnDiagText

const BYTE MINIGAME_KAWIBAWIBO_RESUTLT		= 0x01;		// 가위바위보 결과값
const BYTE MINIGAME_REASSEMBLE_RESULT		= 0x02;		// 퍼즐 결과
const BYTE MINIGAME_REASSEMBLE_OPENWND		= 0x03;		// 퍼즐창 열때 카드아이템 값들을 얻기위해...
const BYTE MINIGAME_ALPHABET_OPENWND		= 0x04;		// 알파벳 창 열때 공개 글자와 위치
const BYTE MINIGAME_ALPHABET_RESULT			= 0x05;		// 알파벳 맞추기 결과
const BYTE MINIGAME_FIVESYSTEM_OPENWND		= 0x06;		// 오곱 창 열때 최소, 최대, 배수
const BYTE MINIGAME_FIVESYSTEM_RESULT		= 0x07;		// 오곱 결과


const BYTE ULTIMATE_MAKEITEM				= 0x01;		// 빛나는 오리칼쿰 생성
const BYTE ULTIMATE_TRANSWEAPON				= 0x02;		// 무기 변환(일반->유니크, 유니크->얼터멋)
const BYTE ULTIMATE_MAKEGEM					= 0x03;		// 보석 생성(아이템 쪼개기)
const BYTE ULTIMATE_SETGEM					= 0x04;		// 보석 합성
const BYTE ULTIMATE_REMOVEGEM				= 0x05;		// 보석 제거
const BYTE ULTIMATE_ENCHANTWEAPON			= 0x06;		// 얼터멋 웨폰 제련

const BYTE LEGENDSKILL_RESULT					= 0x01;		// legend 스킬 결과

const BYTE GI_LOG_VIEW_ITEM_ADD					= 0x01;		// 길드창고 아이템추가 로그
const BYTE GI_LOG_VIEW_ITEM_REMOVE					= 0x02;		// 길드창고 아이템제거 로그
const BYTE GI_LOG_VIEW_MONEY_ADD					= 0x03;		// 길드창고 돈추가 로그
const BYTE GI_LOG_VIEW_MONEY_REMOVE					= 0x04;		// 길드창고 돈추가 로그

const BYTE SECRETROOM_GUILDLIST		= 0x01;
const BYTE SECRETROOM_KILLCOUNT		= 0x02;
const BYTE SECRETROOM_WARSTATE		= 0x03;


#endif //__MSGHDR_H__
